# A project script to organize code for analysis of redistricting maps in
# North Carolina during the 2023 redistricting cycle using techniques and
# map ensembles generated by the Duke Quantifying Gerrymandering team.


# Initial setup -----------------------------------------------------------

# load libraries
library(tidyverse)
library(tidycensus)
library(janitor)
library(ggplot2)
library(jsonlite)
library(googlesheets4)

# set api key for tidycensus
census_api_key(read_lines('keys/census_api', n_max = 1))

#turn off scientific notation
options(scipen = 999)

# Load census files -------------------------------------------------------

# load block level files on NC population from tidycensus
nc_population_block <- get_decennial(geography = "block",
              state = 'NC',
              variables = "P1_001N", 
              year = 2020,
              sumfile = "pl") %>%
  mutate(county = str_extract(NAME, ', ([A-Za-z ]+ County), North Carolina', 1)) %>% 
  select(county, geoid = GEOID, population = value)

nc_population_vtd <- get_decennial(geography = "voting district",
                                   state = 'NC',
                                   variables = "P1_001N", 
                                   year = 2020,
                                   sumfile = "pl") %>%
  mutate(county = str_extract(NAME, ', ([A-Za-z ]+ County), North Carolina', 1),
         vtd = str_extract(NAME, '^(.+), [A-Za-z ]+ County,', 1)) %>% 
  select(county, vtd, geoid = GEOID, population = value)

# readout check of block totals
cat('...loaded', nrow(nc_population_block), 'total blocks from census data...',
    if_else(nrow(nc_population_block) == 236638, 'CHECK', 'ERROR')
)
# readout of population check
cat('...total population', sum(nc_population_block$population), 'calculated from census data...',
    if_else(sum(nc_population_block$population) == 10439388, 'CHECK', 'ERROR')
)

# Load Duke precinct vote to block crosswalk ------------------------------

# The crosswalk file created by the Duke University team contains the vote breakdown
# for multiple statewide races by block, based on precinct level election results.
# Generated from shapefile by exporting to csv using QGIS from
# https://git.math.duke.edu/gitlab/gjh/redistricting2020results/-/blob/main/NC/Shapefiles/cblocks_w20210812Pcts.zip
duke_crosswalk <- read_csv('../data/block_precinct_vote_crosswalk.csv', col_types = cols(geoID = 'c')) %>%
  clean_names('snake') %>% 
  #fix the ss to sst error for 2012
  rename(g12_sst_d = g12_ss_d, g12_sst_r = g12_ss_r)

# readout of population check
cat('...total population', sum(duke_crosswalk$pop2020cen), 'calculated from Duke crosswalk data...',
    if_else(sum(duke_crosswalk$pop2020cen) == 10439388, 'CHECK', 'ERROR')
)

# Load block assignment files ---------------------------------------------

# 2022 maps (used in election)
baf_nc_house22 <-read_csv('../data/baf_nc_house_2022.csv', col_types = cols(.default = 'c') ) %>% clean_names('snake')
baf_nc_senate22 <-read_csv('../data/baf_nc_senate_2022.csv', col_types = cols(.default = 'c') ) %>% clean_names('snake')

baf_us_house22 <-read_csv('../data/baf_us_house_2022.csv', col_types = cols(.default = 'c') ) %>% clean_names('snake')

# 2021 maps (overturned)
baf_nc_house21 <-read_csv('../data/baf_nc_house_2021.csv', col_types = cols(.default = 'c') ) %>% clean_names('snake')
baf_nc_senate21 <-read_csv('../data/baf_nc_senate_2021.csv', col_types = cols(.default = 'c') ) %>% clean_names('snake')

baf_us_house21 <-read_csv('../data/baf_us_house_2021.csv', col_types = cols(.default = 'c') ) %>% clean_names('snake')


# proposed maps
baf_nc_house_h898 <- read_csv('../data/proposed/h898_baf.csv', col_types = cols(.default = 'c') ) %>% 
  clean_names('snake') %>% 
  select(block = geoid20, district)
baf_nc_senate_s758 <- read_csv('../data/proposed/s758_baf.csv', col_types = cols(.default = 'c') ) %>% 
  clean_names('snake') %>% 
  select(block = geoid20, district)

baf_us_house_s756 <- read_csv('../data/proposed/s756_baf.csv', col_types = cols(.default = 'c') ) %>% 
  clean_names('snake') %>% 
  select(block = geoid20, district)
baf_us_house_s757 <- read_csv('../data/proposed/s757_baf.csv', col_types = cols(.default = 'c') ) %>% 
  clean_names('snake') %>% 
  select(block = geoid20, district)

# Function definitions ----------------------------------------------------

#function to generate a table of election results for a given map using
#a provided block assignment file, year and race
#usage
#
#baf_nc_house22 %>% genMapResult('nc_house', 'g20_pr')
genMapResult <- function(baf, chamber, race_code, crosswalk = duke_crosswalk){
  
  #get the ideal population for given chamber
  ideal_pop <- case_when(
    chamber == 'nc_house'~ 10439388/120,
    chamber == 'nc_senate' ~ 10439388/50,
    chamber == 'us_house' ~ 10439388/14,
    .default = 0
  )
  #check for valid entry
  if(ideal_pop == 0){
    cat('X...Error: invalid chamber_code entered')
    break
  }
  
  #narrow down the elections table to the specific race and year
  election_table <- crosswalk %>% 
    select(geo_id, pop2020cen, 
           imputed_votes_dem = paste0(race_code,'_d'),
           imputed_votes_rep = paste0(race_code, '_r'),
           bvap2020cen = bvap2020ce,
           vap2020cen) %>% 
    mutate(imputed_votes_total = imputed_votes_dem + imputed_votes_rep, .after = imputed_votes_rep)
  
  baf %>% 
    left_join(election_table, by = c('block' = 'geo_id')) %>% 
    group_by(district) %>% 
    summarize(population = sum(pop2020cen),
              pop_dev = sum(pop2020cen) - ideal_pop,
              pop_dev_pct = round( ((sum(pop2020cen) - ideal_pop) / ideal_pop) * 100, 2),
              bvap_pct = round( sum(bvap2020cen) / sum(vap2020cen) * 100, 1) ,
              dem_votes = sum(imputed_votes_dem),
              total_votes = sum(imputed_votes_total),
              dem_pct = round( sum(imputed_votes_dem) / (sum(imputed_votes_dem) + sum(imputed_votes_rep) ) * 100 , 1 ),
              party_win = ifelse(sum(imputed_votes_dem) > sum(imputed_votes_rep), 'D', 'R') )
}

#function to generate election tables for an entire list of contests
#showing number of democrats elected
#
#usage
#baf_nc_house22 %>% genElectionTables('nc_house', c('g20_pr', 'g16_pr', 'g12_pr', 'g08_pr'))
genElectionTables <- function(baf, chamber, contest_list, crosswalk = duke_crosswalk){
  
  #get the majority count for given chamber
  majority <- case_when(
    chamber == 'nc_house'~ 120/2 + 1,
    chamber == 'nc_senate' ~ 50/2 + 1,
    chamber == 'us_house' ~ NA,
    .default = 0
  )
  #supermajority
  supermajority <- case_when(
    chamber == 'nc_house'~ 120 * 3/5,
    chamber == 'nc_senate' ~ 50 * 3/5,
    chamber == 'us_house' ~ NA,
    .default = 0
  )

  #initialize an empty ist
  data_list = list()
  
  #loop through the list of contests
  for (i in contest_list){
    race_code = i
    #get the map result for the given contest
    map_result <- baf %>%
      genMapResult(chamber, race_code, crosswalk)
    
    #tally up the seats total vote percentages
    map_summary <- map_result %>%
      arrange(desc(dem_pct)) %>% 
      summarize(
       seats = sum(party_win == 'D'),
       total_dem_votes = sum(dem_votes),
       total_dr_votes = sum(total_votes),
       swing_majority = ifelse(is.na(majority), NA, 50 - nth(dem_pct, majority) ),
       swing_supermajority = ifelse(is.na(supermajority), NA, 50 - nth(dem_pct, supermajority) ),
      ) %>% 
      mutate(dem_pct = round(total_dem_votes/total_dr_votes * 100, 2)) %>% 
      mutate(race_code = race_code, .before = everything())
    
    #assign the contest to a list
    data_list[[race_code]] <- map_summary
    
  }
  
  #collapse the list of contest results to a single dataframe
  election_tables <- data_list %>% 
    bind_rows()
  
  #return the total list of contests
  return(election_tables)

}

#function to tally up number of dems elected across ensemble
#uses path to raw distribution files downloaded from duke team or a preloaded dataframe:
#https://git.math.duke.edu/gitlab/gjh/redistricting2020results/-/tree/main/NC/Ensembles
#also accepts upper and lower boundaries to construct table
#usage:
#
#genHistogramData('../data/ensembles/house/mcd_off/statewide_G20_PR.csv', 45, 65)
genHistogramData <- function(ensemble_data, hist_start, hist_end){
  
  #check for dataframe and read in file if its a path
  if(!is.data.frame(ensemble_data)){
    ensemble_data <- read_csv(ensemble_data, show_col_types = FALSE)
  }
  
  #generate a single-column dataframe using provided boundaries
  data.frame(dems_elected = c(hist_start:hist_end)) %>% 
    #join with the raw distribution file after processing
    left_join(
      ensemble_data %>%
        #calculate the number of dems elected by counting vote totals above 50%
        mutate(dems_elected = rowSums(. > 0.5)) %>% 
        select(dems_elected) %>%
        #group by the number of dems elected to get the distribution across all maps
        count(dems_elected, name = 'map_count'),
      by = 'dems_elected'
    ) %>%
    #replace any nulls with zero
    replace_na(list(map_count = 0) ) %>%
    #reformat the percentages
    mutate(hist_pct = round(map_count/100000 * 100, 1) )
}

#function to produce a histogram using duke ensemble performance data
#and performance of a given map proposal. accepts a two-digit year,
#a race, and a preloaded block assignment file.
#
#syntax:
#genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_PR.csv', 'g20_pr', 'us_house', baf_us_house22)
genHistogramChart <- function(raw_file_path, race_code, chamber, baf, mcd = 1){
  
  #set the mcd status, default is on
  mcd_status <- ifelse(mcd == 1, 'on', 'off')
  
  hist_start <- case_when(
    chamber == 'nc_house' ~ 35,
    chamber == 'nc_senate' ~ 10,
    chamber == 'us_house' ~ 0,
    .default = NA
  )
  hist_end <- case_when(
    chamber == 'nc_house' ~ 75,
    chamber == 'nc_senate' ~ 35,
    chamber == 'us_house' ~ 14,
    .default = NA
  )
  #check for valid entry
  if(is.na(hist_start) | is.na(hist_end)){
    cat('X...Error: invalid chamber_code entered')
    break
  }
  
  seat_count <- baf %>%
    genMapResult(chamber, race_code) %>%
    summarize(seats = sum(party_win == 'D')) %>%
    pull(seats)
  
  #generate the source data
  genHistogramData(raw_file_path, hist_start, hist_end) %>% {
    #base plot data
    ggplot(., aes(dems_elected,
                  hist_pct,
                  yend = 60,
                  fill = ifelse( hist_pct == max(hist_pct), 'highlight', 'normal') )
    ) +
      geom_col() +
      #set annotation of mode value with a curved arrow
      annotate(
        geom = "curve",
        x = .[which(.$hist_pct == max(.$hist_pct)), "dems_elected"] + 5,
        y = max(.$hist_pct) + 10,
        xend = .[which(.$hist_pct == max(.$hist_pct)), "dems_elected"],
        yend = max(.$hist_pct) + 0.5, 
        curvature = .3, arrow = arrow(length = unit(2, "mm"))
      ) +
      #set annotation of mode value with label text
      annotate(geom = "text",
               x = .[which(.$hist_pct == max(.$hist_pct)), "dems_elected"] + 5.25,
               y = max(.$hist_pct) + 10,
               label = "most common result\nacross 100,000 maps",
               lineheight = 0.9,
               hjust = "left"
      ) +
      #generate point showing map proposal value for comparison
      geom_point( aes(x = seat_count,
                      y = 1),
                  color = '#fc8d62',
                  size = 3
      ) +
      #set annotation of proposal value with curved arrow
      annotate(
        geom = "curve",
        x = seat_count - 5,
        y = 9,
        xend = seat_count - 0.2,
        yend = 2.5, 
        curvature = -0.3, arrow = arrow(length = unit(2, "mm"))
      ) +
      #set annotation of proposal value with label text
      annotate(geom = "text",
               x = seat_count - 5.25,
               y = 9,
               label = "how this map\nperformed",
               lineheight = 0.9,
               hjust = "right"
      ) +
      #color the bars
      scale_fill_manual(values=c('gray40', 'gray80')) +
      #customize the breaks on the x axis
      scale_x_continuous(breaks = seq(from = hist_start, to = hist_end, by = 5),
                         minor_breaks = seq(from = hist_start, to = hist_end, by = 1)
      ) +
      #customize the y axis
      scale_y_continuous(breaks = seq(from = 0, to = 60, by = 10)) +
      #add labels based on inputs
      labs(
        x = '# OF DEMOCRATS ELECTED', y = '% OF MAPS WITH RESULT',
        title = paste0('How the maps performed: ', chamber),
        subtitle = paste0(toupper(race_code), ', MCD ', toupper(mcd_status)),
        caption = 'SOURCE: Duke Quantifying Gerrymandering team, N&O analysis'
      ) +
      theme_minimal() +
      theme(legend.position = "none")
  }
}

# Run a uniform swing analysis with a given interval
#
# usage
# genSwingVotes(baf_nc_senate21, 'nc_senate', 'g20_pr', 0.005, 0.05)
genSwingVotes <- function(baf, chamber, race_code, interval, max_swing, crosswalk = duke_crosswalk){
  
  #create a vector of swing values to adjust votes by
  swing_values <- seq(from = interval, to = max_swing, by = interval)
  
  #establish d and r col
  d_col = paste0(race_code, '_d')
  r_col = paste0(race_code, '_r')
  
  #construct a new crosswalk using the swing values
  swing_crosswalk <- crosswalk %>% 
    select(geo_id:pop2020cen, vap2020cen, bvap2020ce,
           !!d_col, !!r_col )
  
  swing_crosswalk <- swing_crosswalk %>% 
    mutate(total_dr = !!as.name(d_col) + !!as.name(r_col) )
  
  for(value in swing_values){
    swing_crosswalk <- swing_crosswalk %>% 
      mutate('{race_code}_{value}_d' := !!as.name(d_col) + total_dr * value,
             '{race_code}_{value}_r' := !!as.name(r_col) - total_dr * value)
  }
  
  #use swing values to create vector of contest list race codes
  contest_list <- append(race_code, paste0(race_code, '_', swing_values) )
  
  #generate the election tables
  genElectionTables(baf, chamber, contest_list, crosswalk = swing_crosswalk )
  
}

# Use uniform swing analysis to generate a table of most common values from 
# the Duke ensemble for a given interval and max swing.
#
# usage
# genEnsembleSwing('../data/ensembles/house/mcd_on/statewide_G20_PR.csv', 'g20_pr', 0.005, 0.05)
genEnsembleSwing <- function(ensemble_data_path, race_code, interval, max_swing){
  
  #create a vector of swing values to adjust votes by
  swing_values <- seq(from = interval, to = max_swing, by = interval)
  
  #initialize the simplified histogram data
  base_election <- read_csv(ensemble_data_path, show_col_types = FALSE)
  
  histogram_data <- base_election %>% 
    genHistogramData(0, 120) %>%
    filter(map_count == max(map_count)) %>% 
    mutate(race_code = race_code, .before = everything())
  
  #loop through the vector of swing values to add to the histogram data
  for(value in swing_values){
    swing_election <- base_election %>% 
      mutate(across(everything(), ~ .x + value)) %>% 
      genHistogramData(0, 120) %>%
      filter(map_count == max(map_count)) %>% 
      mutate(race_code = paste0(race_code, '_', value), .before = everything())
    
    histogram_data <- histogram_data %>% 
      rbind(swing_election)
  }
  
  histogram_data <- histogram_data %>% 
    rename(hist_mode_dems = dems_elected, hist_count = map_count)
  
  return(histogram_data)
  
}

#dem_pct, democrats, republicans
genSwingJSON <- function(swing_data){
  
  #initialize an emtpy list
  swing_list <- list()
  
  #iterate through the swing data to reformat the list
  for(row in 1:nrow(swing_data)){
    list_item <- list(list(democrats = swing_data[row, 'democrats'][[1]],
                           republicans = swing_data[row, 'republicans'][[1]]))
    swing_list[as.character(swing_data[row, 'dem_pct'][[1]])] <- list_item
  }
  
  swing_json <- swing_list %>% 
    toJSON(auto_unbox = TRUE, pretty = TRUE )
  
  return(swing_json)
  
}

#dems_elected, map_count
genHistogramJSON <- function(histogram_data){
  histogram_json <- setNames(as.list(histogram_data$map_count),
           as.list(histogram_data$dems_elected)
           ) %>%
    toJSON(auto_unbox = TRUE, pretty = TRUE )
  
  return(histogram_json)
}

# Test functions ----------------------------------------------------------

election_tables <- baf_us_house22 %>% 
  genElectionTables('us_house', c('g20_pr', 'g16_pr', 'g12_pr', 'g08_pr'))

#readout of vote check
for(row in 1:nrow(election_tables)){
  cat('...Dem votes for', election_tables[row, 'race_code'][[1]], election_tables[row, 'total_dem_votes'][[1]], 
      'calculated from imputed maps...',
      if_else(election_tables[row, 'total_dem_votes'][[1]] == sum(duke_crosswalk[[paste0(election_tables[row, 'race_code'][[1]], '_d')]]), 
              'CHECK', 'ERROR'),
      '\n'
  )
  
  cat('...Dem + Rep votes for', election_tables[row, 'race_code'][[1]], election_tables[row, 'total_dr_votes'][[1]], 
      'calculated from imputed maps...',
      if_else(election_tables[row, 'total_dr_votes'][[1]] == sum(duke_crosswalk[[paste0(election_tables[row, 'race_code'][[1]], '_d')]]) + sum(duke_crosswalk[[paste0(election_tables[row, 'race_code'][[1]], '_r')]]), 
              'CHECK', 'ERROR'),
      '\n'
  )
}

baf_us_house22 %>% 
  genElectionTables('us_house', c('g20_pr', 'g16_pr', 'g12_pr', 'g08_pr')) %>% 
  arrange(dem_pct)

baf_us_house21 %>% 
  genElectionTables('us_house', c('g12_gv', 'g20_ca', 'g16_lg', 'g16_uss', 'g20_tr', 'g16_pr',
                                  'g20_lg', 'g12_pr', 'g20_pr', 'g20_ag', 'g20_ad', 'g20_sst', 
                                  'g12_ci', 'g20_gv', 'g12_sst', 'g08_uss')) %>% 
  arrange(dem_pct)

baf_nc_house22 %>% 
  genElectionTables('nc_house', c('g20_pr', 'g16_pr', 'g12_pr', 'g08_pr')) %>% 
  arrange(dem_pct)

baf_nc_house21 %>% 
  genElectionTables('nc_house', c('g20_pr', 'g16_pr', 'g12_pr', 'g08_pr')) %>% 
  arrange(dem_pct)

genHistogramData('../data/ensembles/congressional/atlas_measureID12_marginals_G20_PR.csv', 1, 14)

genHistogramData('../data/ensembles/congressional/atlas_measureID12_marginals_G20_PR.csv', 1, 14)

genHistogramChart('g20_pr', 'us_house', 
                  '../data/ensembles/congressional/atlas_measureID12_marginals_G20_PR.csv', baf_us_house22)

baf_nc_house21 %>% 
  genElectionTables('us_house', c('g12_gv', 'g20_ca', 'g16_lg', 'g16_uss', 'g20_tr', 'g16_pr',
                                  'g20_lg', 'g12_pr', 'g20_pr', 'g20_ag', 'g20_ad', 'g20_sst', 
                                  'g12_ci', 'g20_gv', 'g12_sst', 'g08_uss')) %>% 
  arrange(dem_pct)

# g12_gv  g16_pr g20_pr g20_gv g08_uss
genHistogramChart('g12_gv', 'nc_house', 
                  '../data/ensembles/house/mcd_on/statewide_G12_GV.csv', baf_nc_house21)

genHistogramChart('g16_pr', 'nc_house', 
                  '../data/ensembles/house/mcd_on/statewide_G16_PR.csv', baf_nc_house21)

genHistogramChart('g20_pr', 'nc_house', 
                  '../data/ensembles/house/mcd_on/statewide_G20_PR.csv', baf_nc_house21)

genHistogramChart('g20_gv', 'nc_house', 
                  '../data/ensembles/house/mcd_on/statewide_G20_GV.csv', baf_nc_house21)

genHistogramChart('g08_uss', 'nc_house', 
                  '../data/ensembles/house/mcd_on/statewide_G08_USS.csv', baf_nc_house21)

genHistogramChart('g20_pr', 'nc_house', 
                  '../data/ensembles/house/mcd_on/statewide_G20_PR.csv', baf_nc_house21)


# Generate results of original and remedial maps --------------------------

#store all contests for ease of use
all_contests <- c('g08_pr', 'g08_uss', 'g08_gv', 'g08_lg', 'g08_ag', 'g08_ad', 'g08_ca', 'g08_ci', 'g08_cl', 
                  'g10_uss',
                  'g12_pr', 'g12_gv', 'g12_lg', 'g12_sst', 'g12_ci',  
                  'g14_uss',
                  'g16_pr', 'g16_gv', 'g16_lg', 'g16_uss', 'g16_ag',
                  'g20_pr', 'g20_uss', 'g20_gv', 'g20_lg', 'g20_ag', 'g20_ca', 'g20_tr', 'g20_ad', 'g20_sst', 'g20_ci', 'g20_cl'
)

#nc house
nc_house_results <- baf_nc_house21 %>% 
  genElectionTables('nc_house', all_contests) %>% 
  mutate(dems_original = seats) %>% 
  left_join(
    baf_nc_house22 %>% 
      genElectionTables('nc_house', all_contests) %>% 
      select(race_code, dems_remedial = seats),
    by = 'race_code'
  ) %>% 
  arrange(dem_pct) %>% 
  mutate(Difference = dems_remedial - dems_original)

#nc senate
nc_senate_results <- baf_nc_senate21 %>% 
  genElectionTables('nc_senate', all_contests) %>% 
  mutate(dems_original = seats) %>% 
  left_join(
    baf_nc_senate22 %>% 
      genElectionTables('nc_senate', all_contests) %>% 
      select(race_code, dems_remedial = seats),
    by = 'race_code'
  ) %>% 
  arrange(dem_pct) %>% 
  mutate(Difference = dems_remedial - dems_original)

#us house/congress
us_house_results <- baf_us_house21 %>% 
  genElectionTables('us_house', all_contests) %>% 
  mutate(dems_original = seats) %>% 
  left_join(
    baf_us_house22 %>% 
      genElectionTables('us_house', all_contests) %>% 
      select(race_code, dems_remedial = seats),
    by = 'race_code'
  ) %>% 
  arrange(dem_pct) %>% 
  mutate(Difference = dems_remedial - dems_original)

#clean up the results for posting to GitHub
nc_house_results %>% 
  select('Contest and year' = race_code, 'Statewide D vote %' = dem_pct,
         'D seats, original map' = dems_original, 'D seats, final map' = dems_remedial, Difference) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()

nc_senate_results %>% 
  select('Contest and year' = race_code, 'Statewide D vote %' = dem_pct,
         'D seats, original map' = dems_original, 'D seats, final map' = dems_remedial, Difference) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()

us_house_results %>% 
  select('Contest and year' = race_code, 'Statewide D vote %' = dem_pct,
         'D seats, original map' = dems_original, 'D seats, final map' = dems_remedial, Difference) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()

#examine governor 12 for NC Senate
baf_nc_senate21 %>%
  genMapResult('nc_senate', 'g12_gv') %>% 
  mutate(d_win = if_else(party_win == 'D', 1, 0)) %>%
  arrange(desc(district)) %>% 
  write_csv('../data/gv12_detail.csv')


# Additional histogram data -----------------------------------------------

genHistogramData('../data/ensembles/house/mcd_on/statewide_G12_GV.csv', 0, 120) %>% 
  write_csv('../data/ensembles/histogram_data/g12_gv_mcd_on.csv')

genHistogramData('../data/ensembles/house/mcd_on/statewide_G16_PR.csv', 0, 120) %>% 
  write_csv('../data/ensembles/histogram_data/g16_pr_mcd_on.csv')

genHistogramData('../data/ensembles/house/mcd_on/statewide_G20_PR.csv', 0, 120) %>% 
  write_csv('../data/ensembles/histogram_data/g20_pr_mcd_on.csv')

genHistogramData('../data/ensembles/house/mcd_on/statewide_G20_GV.csv', 0, 120) %>% 
  write_csv('../data/ensembles/histogram_data/g20_gv_mcd_on.csv')

genHistogramData('../data/ensembles/house/mcd_on/statewide_G08_USS.csv', 0, 120) %>% 
  write_csv('../data/ensembles/histogram_data/g08_uss_mcd_on.csv')


# Uniform swing analysis --------------------------------------------------

genMapResult(baf_nc_senate21, 'nc_senate', 'g20_pr') %>% 
  arrange(desc(dem_pct)) %>% 
  summarize(median = median(dem_pct),
            win = nth(dem_pct, 26))

genMapResult(baf_nc_house21, 'nc_house', 'g20_pr') %>% 
  arrange(desc(dem_pct)) %>% 
  view()

genElectionTables(baf_nc_house21, 'nc_house', 'g20_pr')
genElectionTables(baf_nc_senate21, 'nc_senate', 'g20_pr')

genElectionTables(baf_nc_house22, 'nc_house', 'g20_pr')
genElectionTables(baf_nc_senate22, 'nc_senate', 'g20_pr')

genSwingVotes(baf_nc_senate21, 'nc_senate', 'g20_pr', 0.005, 0.05)

#get the mode of the 

read_csv('../data/ensembles/house/mcd_on/statewide_G20_PR.csv', show_col_types = FALSE) %>% 
  genHistogramData(45, 65) %>%
  filter(map_count == max(map_count))

read_csv('../data/ensembles/house/mcd_on/statewide_G20_PR.csv', show_col_types = FALSE) %>% 
  mutate(across(everything(), ~ .x + 0.005)) %>% 
  genHistogramData(0, 120) %>%
  filter(map_count == max(map_count)) %>% 
  mutate(race_code = 'g20_pr_0.005', .before = everything())

read_csv('../data/ensembles/senate/mcd_on/statewide_G20_PR.csv', show_col_types = FALSE) %>% 
  mutate(across(everything(), ~ .x + 0.005)) %>% 
  genHistogramData(0, 120) %>%
  filter(map_count == max(map_count)) %>% 
  mutate(race_code = 'g20_pr_0.005', .before = everything())
  

genEnsembleSwing('../data/ensembles/house/mcd_on/statewide_G20_PR.csv', 'g20_pr', 0.005, 0.05)
genHistogramData('../data/ensembles/house/mcd_off/statewide_G20_PR.csv', 45, 65)

genSwingVotes(baf_nc_house21, 'nc_house', 'g20_pr', 0.005, 0.05) %>% 
  left_join(
    genEnsembleSwing('../data/ensembles/house/mcd_on/statewide_G20_PR.csv', 'g20_pr', 0.005, 0.05),
    by = 'race_code'
  )

#simplify for gh
genSwingVotes(baf_nc_house21, 'nc_house', 'g20_pr', 0.005, 0.05) %>% 
  left_join(
    genEnsembleSwing('../data/ensembles/house/mcd_on/statewide_G20_PR.csv', 'g20_pr', 0.005, 0.05),
    by = 'race_code'
  ) %>%
  mutate('Statewide D vote %' = round(total_dem_votes / total_dr_votes * 100, 1)) %>%
  select(
    'Contest and year' = race_code,
    'Statewide D vote %',
    'D Seats, original map' = seats,
    'D Seats, ensemble mode' = hist_mode_dems,
    '% of ensemble' = hist_pct
  ) %>% 
  knitr::kable('pipe') %>% 
  clipr::write_clip()

genSwingVotes(baf_nc_house21, 'nc_house', 'g20_gv', 0.005, 0.05) %>% 
  left_join(
    genEnsembleSwing('../data/ensembles/house/mcd_on/statewide_G20_GV.csv', 'g20_gv', 0.005, 0.05),
    by = 'race_code'
  ) %>%
  mutate('Statewide D vote %' = round(total_dem_votes / total_dr_votes * 100, 1)) %>%
  select(
    'Contest and year' = race_code,
    'Statewide D vote %',
    'D Seats, original map' = seats,
    'D Seats, ensemble mode' = hist_mode_dems,
    '% of ensemble' = hist_pct
  ) %>% 
  knitr::kable('pipe') %>% 
  clipr::write_clip()

genSwingVotes(baf_nc_senate21, 'nc_senate', 'g20_pr', 0.005, 0.05) %>% 
  left_join(
    genEnsembleSwing('../data/ensembles/senate/mcd_on/statewide_G20_PR.csv', 'g20_pr', 0.005, 0.05),
    by = 'race_code'
  ) %>%
  mutate('Statewide D vote %' = round(total_dem_votes / total_dr_votes * 100, 1)) %>%
  select(
    'Contest and year' = race_code,
    'Statewide D vote %',
    'D Seats, original map' = seats,
    'D Seats, ensemble mode' = hist_mode_dems,
    '% of ensemble' = hist_pct
  ) %>% 
  knitr::kable('pipe') %>% 
  clipr::write_clip()

genSwingVotes(baf_nc_senate21, 'nc_senate', 'g20_gv', 0.005, 0.05) %>% 
  left_join(
    genEnsembleSwing('../data/ensembles/senate/mcd_on/statewide_G20_gv.csv', 'g20_gv', 0.005, 0.05),
    by = 'race_code'
  ) %>%
  mutate('Statewide D vote %' = round(total_dem_votes / total_dr_votes * 100, 1)) %>% 
  select(
    'Contest and year' = race_code,
    'Statewide D vote %',
    'D Seats, original map' = seats,
    'D Seats, ensemble mode' = hist_mode_dems,
    '% of ensemble' = hist_pct
  ) %>% 
  knitr::kable('pipe') %>%
  clipr::write_clip()

#examine this one closer
genHistogramChart('../data/ensembles/senate/mcd_on/statewide_G20_PR.csv', 'g20_pr', 'nc_senate', baf_nc_senate21)
genHistogramData('../data/ensembles/senate/mcd_on/statewide_G20_PR.csv', 0, 50)

read_csv('../data/ensembles/senate/mcd_on/statewide_G20_PR.csv', show_col_types = FALSE) %>% 
  mutate(across(everything(), ~ .x + 0.045)) %>% 
  genHistogramChart('g20_pr', 'nc_senate', baf_nc_senate21)


# Produce relevant JSON ---------------------------------------------------
#
# responsive/unresponsive map format
# {
#   "30": {"democrats": 21, "republicans": 29},
#   "31": {"democrats": 22, "republicans": 28}
# }

#single map responsiveness json
genSwingVotes(baf_nc_senate21, 'nc_senate', 'g20_pr', 0.005, 0.05) %>% 
  left_join(
    genEnsembleSwing('../data/ensembles/senate/mcd_on/statewide_G20_PR.csv', 'g20_pr', 0.005, 0.05),
    by = 'race_code'
  ) %>%
  mutate(dem_pct = round(total_dem_votes / total_dr_votes * 100, 1),
         republicans_single = 50 - seats,
         republicans_ensemble = 50 - hist_mode_dems) %>% 
  select(dem_pct,
         democrats_single = seats, republicans_single,
         democrats_ensemble = hist_mode_dems, republicans_ensemble) %>% 
  select(dem_pct, contains('_single')) %>% 
  rename_with(~str_remove(., '_single')) %>% 
  genSwingJSON() %>% 
  write('../data/json/responsive_g20_pr_senate_original.json')

#ensemble map responsiveness json
genSwingVotes(baf_nc_senate21, 'nc_senate', 'g20_pr', 0.005, 0.05) %>% 
  left_join(
    genEnsembleSwing('../data/ensembles/senate/mcd_on/statewide_G20_PR.csv', 'g20_pr', 0.005, 0.05),
    by = 'race_code'
  ) %>%
  mutate(dem_pct = round(total_dem_votes / total_dr_votes * 100, 1),
         republicans_single = 50 - seats,
         republicans_ensemble = 50 - hist_mode_dems) %>% 
  select(dem_pct,
         democrats_single = seats, republicans_single,
         democrats_ensemble = hist_mode_dems, republicans_ensemble) %>% 
  select(dem_pct, contains('_ensemble')) %>% 
  rename_with(~str_remove(., '_ensemble')) %>% 
  genSwingJSON() %>% 
  write('../data/json/responsive_g20_pr_senate_ensemble.json')


# histogram format
# {"30":0,"31":0,"32":0,"33":0,"34":0,"35":0,"36":0,"37":0,"38":0,"39":0,"40":0,
# "41":0,"42":0,"43":0,"44":0,"45":0,"46":0,"47":0,"48":0,"49":0,"50":0,"51":0,
# "52":0,"53":0,"54":0,"55":0,"56":0,"57":0,"58":0,"59":0,"60":0,"61":0,"62":0,
# "63":0,"64":1,"65":79,"66":830,"67":4051,"68":11308,"69":19747,"70":23973,"71":20897,
# "72":12663,"73":5081,"74":1223,"75":137,"76":9,"77":1,"78":0,"79":0,"80":0}
#

hist_json <- genHistogramData('../data/ensembles/house/mcd_on/statewide_G20_PR.csv', 30, 80) %>% 
  select(dems_elected, map_count)

setNames(as.list(hist_json$map_count),
           as.list(hist_json$dems_elected)
  ) %>% 
  toJSON(auto_unbox = TRUE, pretty = TRUE )

hist_json <- genHistogramData('../data/ensembles/house/mcd_on/statewide_G20_PR.csv', 30, 80) %>% 
  select(dems_elected, map_count) %>% 
  genHistogramJSON() %>% 
  write('../data/json/histogram_g20_pr_house.json')



# Working with proposed maps ----------------------------------------------

nc_house_tables <- baf_nc_house_h898 %>% genElectionTables('nc_house', all_contests)

nc_senate_tables <- baf_nc_senate_s758 %>% genElectionTables('nc_senate', all_contests)

us_congress1_tables <- baf_us_house_s756 %>% genElectionTables('us_house', all_contests)

us_congress2_tables <- baf_us_house_s757 %>% genElectionTables('us_house', all_contests)

genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_PR.csv', 'g20_pr', 'us_house', baf_us_house22)

genHistogramChart('../data/ensembles/house/mcd_on/statewide_G20_PR.csv', 'g20_pr', 'nc_house', baf_nc_house_h898)
genHistogramChart('../data/ensembles/house/mcd_on/statewide_G20_GV.csv', 'g20_gv', 'nc_house', baf_nc_house_h898)
genHistogramChart('../data/ensembles/house/mcd_on/statewide_G20_LG.csv', 'g20_lg', 'nc_house', baf_nc_house_h898)
genHistogramChart('../data/ensembles/house/mcd_on/statewide_G12_GV.csv', 'g12_gv', 'nc_house', baf_nc_house_h898)
genHistogramChart('../data/ensembles/house/mcd_on/statewide_G16_PR.csv', 'g16_pr', 'nc_house', baf_nc_house_h898)
genHistogramChart('../data/ensembles/house/mcd_on/statewide_G08_USS.csv', 'g08_uss', 'nc_house', baf_nc_house_h898)

genHistogramData('../data/ensembles/house/mcd_on/statewide_G20_PR.csv', 45, 65)
genHistogramData('../data/ensembles/house/mcd_on/statewide_G12_GV.csv', 30, 65)
genHistogramData('../data/ensembles/house/mcd_on/statewide_G16_PR.csv', 30, 65)

genHistogramChart('../data/ensembles/senate/mcd_on/statewide_G20_PR.csv', 'g20_pr', 'nc_senate', baf_nc_senate_s758)
genHistogramChart('../data/ensembles/senate/mcd_on/statewide_G20_GV.csv', 'g20_gv', 'nc_senate', baf_nc_senate_s758)
genHistogramChart('../data/ensembles/senate/mcd_on/statewide_G20_LG.csv', 'g20_lg', 'nc_senate', baf_nc_senate_s758)

genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_PR.csv', 'g20_pr', 'us_house', baf_us_house_s756)
genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_GV.csv', 'g20_gv', 'us_house', baf_us_house_s756)
genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_LG.csv', 'g20_lg', 'us_house', baf_us_house_s756)

genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_PR.csv', 'g20_pr', 'us_house', baf_us_house_s757)
genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_GV.csv', 'g20_gv', 'us_house', baf_us_house_s757)
genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_LG.csv', 'g20_lg', 'us_house', baf_us_house_s757)

#generate proposal map json
genSwingVotes(baf_nc_senate_s758, 'nc_senate', 'g20_pr', 0.005, 0.05) %>% 
  left_join(
    genEnsembleSwing('../data/ensembles/senate/mcd_on/statewide_G20_PR.csv', 'g20_pr', 0.005, 0.05),
    by = 'race_code'
  ) %>%
  mutate(dem_pct = round(total_dem_votes / total_dr_votes * 100, 1),
         republicans_single = 50 - seats,
         republicans_ensemble = 50 - hist_mode_dems) %>% 
  select(dem_pct,
         democrats_single = seats, republicans_single,
         democrats_ensemble = hist_mode_dems, republicans_ensemble) %>% 
  select(dem_pct, contains('_single')) %>% 
  rename_with(~str_remove(., '_single')) %>% 
  genSwingJSON() %>% 
  write('../data/json/responsive_g20_pr_senate_s758.json')

genSwingVotes(baf_nc_house_h898, 'nc_house', 'g20_pr', 0.005, 0.05) %>%
  left_join(
    genEnsembleSwing('../data/ensembles/house/mcd_on/statewide_G20_PR.csv', 'g20_pr', 0.005, 0.05),
    by = 'race_code'
  ) %>%
  mutate(dem_pct = round(total_dem_votes / total_dr_votes * 100, 1),
         republicans_single = 120 - seats,
         republicans_ensemble = 120 - hist_mode_dems) %>% 
  select(dem_pct,
         democrats_single = seats, republicans_single,
         democrats_ensemble = hist_mode_dems, republicans_ensemble) %>% 
  select(dem_pct, contains('_single')) %>% 
  rename_with(~str_remove(., '_single')) %>% 
  genSwingJSON() %>% 
  write('../data/json/responsive_g20_pr_house_h898.json')

#comparison tables
#nc house
nc_house_results <- baf_nc_house_h898 %>% 
  genElectionTables('nc_house', all_contests) %>% 
  mutate(dems_2023 = seats) %>% 
  left_join(
    baf_nc_house22 %>% 
      genElectionTables('nc_house', all_contests) %>% 
      select(race_code, dems_2022 = seats),
    by = 'race_code'
  ) %>% 
  arrange(dem_pct) %>% 
  mutate(Difference = dems_2023 - dems_2022)

#nc senate
nc_senate_results <- baf_nc_senate_s758 %>% 
  genElectionTables('nc_senate', all_contests) %>% 
  mutate(dems_2023 = seats) %>% 
  left_join(
    baf_nc_senate22 %>% 
      genElectionTables('nc_senate', all_contests) %>% 
      select(race_code, dems_2022 = seats),
    by = 'race_code'
  ) %>% 
  arrange(dem_pct) %>% 
  mutate(Difference = dems_2023 - dems_2022)

#us house/congress
us_house_results756 <- baf_us_house_s756 %>% 
  genElectionTables('us_house', all_contests) %>% 
  mutate(dems_2023 = seats) %>% 
  left_join(
    baf_us_house22 %>% 
      genElectionTables('us_house', all_contests) %>% 
      select(race_code, dems_2022 = seats),
    by = 'race_code'
  ) %>% 
  arrange(dem_pct) %>% 
  mutate(Difference =  dems_2023 - dems_2022)

us_house_results757 <- baf_us_house_s757 %>% 
  genElectionTables('us_house', all_contests) %>% 
  mutate(dems_2023 = seats) %>% 
  left_join(
    baf_us_house22 %>% 
      genElectionTables('us_house', all_contests) %>% 
      select(race_code, dems_2022 = seats),
    by = 'race_code'
  ) %>% 
  arrange(dem_pct) %>% 
  mutate(Difference = dems_2023 - dems_2022)



nc_house_results %>% 
  select('Contest and year' = race_code, 'Statewide D vote %' = dem_pct,
         'D seats, 2023 map' = dems_2023, 'D seats, 2022 map' = dems_2022, Difference) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()

nc_senate_results %>% 
  select('Contest and year' = race_code, 'Statewide D vote %' = dem_pct,
         'D seats, 2023 map' = dems_2023, 'D seats, 2022 map' = dems_2022, Difference) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()

us_house_results756 %>% 
  select('Contest and year' = race_code, 'Statewide D vote %' = dem_pct,
         'D seats, 2023 map' = dems_2023, 'D seats, 2022 map' = dems_2022, Difference) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()

us_house_results757 %>% 
  select('Contest and year' = race_code, 'Statewide D vote %' = dem_pct,
         'D seats, 2023 map' = dems_2023, 'D seats, 2022 map' = dems_2022, Difference) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()
