# A project script to organize code for analysis of redistricting maps in
# North Carolina during the 2023 redistricting cycle using techniques and
# map ensembles generated by the Duke Quantifying Gerrymandering team.
#
# by Tyler Dukes, The News & Observer

# Initial setup -----------------------------------------------------------

# load libraries
library(tidyverse)
library(janitor)

# for making motion graphics
library(magick)

# for producing json for interactive
library(jsonlite)

# turn off scientific notation
options(scipen = 999)

# Load Duke precinct vote to block crosswalk ------------------------------

# The crosswalk file created by the Duke University team contains the vote breakdown
# for multiple statewide races by block, based on precinct level election results.
# Generated from shapefile by exporting to csv using QGIS from
# https://git.math.duke.edu/gitlab/gjh/redistricting2020results/-/blob/main/NC/Shapefiles/cblocks_w20210812Pcts.zip
duke_crosswalk <- read_csv('../data/block_precinct_vote_crosswalk.csv', col_types = cols(geoID = 'c')) %>%
  clean_names('snake') %>% 
  #fix the ss to sst error for 2012
  rename(g12_sst_d = g12_ss_d, g12_sst_r = g12_ss_r)

# readout of population check
cat('...total population', sum(duke_crosswalk$pop2020cen), 'calculated from Duke crosswalk data...',
    if_else(sum(duke_crosswalk$pop2020cen) == 10439388, 'CHECK', 'ERROR')
)

# store all contest codes for ease of use
# in crosswalk data but not in ensemble data: 'g08_gv', 'g08_lg', 'g08_ag', 'g08_cl', 'g08_ad', 'g08_ca', 'g10_uss'
# in ensemble data but not in crosswalk data: 'g12_tr
# NOTE: Filenames for 2012 Sec. of State were changed from G12_SS to G12_SST for consistency
all_contests <- c('g08_pr', 'g08_uss','g08_ci',
                  #'g08_gv', 'g08_lg', 'g08_ag', 'g08_cl', 'g08_ad', 'g08_ca',
                  #'g10_uss',
                  'g12_pr', 'g12_gv', 'g12_lg', 'g12_sst', 'g12_ci',  
                  'g14_uss',
                  'g16_pr', 'g16_gv', 'g16_lg', 'g16_uss', 'g16_ag',
                  'g20_pr', 'g20_uss', 'g20_gv', 'g20_lg', 'g20_ag', 'g20_ca', 'g20_tr', 'g20_ad', 'g20_sst', 'g20_ci', 'g20_cl'
)

# Load block assignment files ---------------------------------------------

# 2022 maps (used in election)
baf_nc_house22 <- read_csv('../baf/baf_nc_house_2022.csv', col_types = cols(.default = 'c') ) %>% clean_names('snake')
baf_nc_senate22 <- read_csv('../baf/baf_nc_senate_2022.csv', col_types = cols(.default = 'c') ) %>% clean_names('snake')
baf_us_house22 <- read_csv('../baf/baf_us_house_2022.csv', col_types = cols(.default = 'c') ) %>% clean_names('snake')

# 2021 maps (overturned)
baf_nc_house21 <-read_csv('../baf/baf_nc_house_2021.csv', col_types = cols(.default = 'c') ) %>% clean_names('snake')
baf_nc_senate21 <-read_csv('../baf/baf_nc_senate_2021.csv', col_types = cols(.default = 'c') ) %>% clean_names('snake')
baf_us_house21 <-read_csv('../baf/baf_us_house_2021.csv', col_types = cols(.default = 'c') ) %>% clean_names('snake')

# proposed maps
baf_nc_house_h898 <- read_csv('../baf/h898_baf.csv', col_types = cols(.default = 'c') ) %>% 
  clean_names('snake') %>% 
  select(block = geoid20, district)
baf_nc_senate_s758 <- read_csv('../baf/s758_baf.csv', col_types = cols(.default = 'c') ) %>% 
  clean_names('snake') %>% 
  select(block = geoid20, district)
### NOT ENACTED
baf_us_house_s756 <- read_csv('../baf/s756_baf.csv', col_types = cols(.default = 'c') ) %>% 
  clean_names('snake') %>% 
  select(block = geoid20, district)
###
baf_us_house_s757 <- read_csv('../baf/s757_baf.csv', col_types = cols(.default = 'c') ) %>% 
  clean_names('snake') %>% 
  select(block = geoid20, district)

# enacted maps
baf_nc_house_h898_ed3 <- read_csv('../baf/baf_h898_ed3.csv', col_types = cols(.default = 'c') ) %>% clean_names('snake')
baf_nc_senate_s758_ed2 <- read_csv('../baf/baf_s758_ed2.csv', col_types = cols(.default = 'c') ) %>% clean_names('snake')
baf_us_house_s757_ed2 <- read_csv('../baf/baf_s757_ed2.csv', col_types = cols(.default = 'c') ) %>% clean_names('snake')

# Function definitions ----------------------------------------------------

# function to convert race code into plain language year and contest
# 
# usage
# parseRaceCode('g08_pr')
parseRaceCode <- function(race_code){
  
  parsed_race_code <- case_when(
    race_code == 'g08_pr' ~ '2008 president',
    race_code == 'g08_uss' ~ '2008 U.S. Senate',
    race_code == 'g08_gv' ~ '2008 governor',
    race_code == 'g08_lg' ~ '2008 lieutenant governor',
    race_code == 'g08_ag' ~ '2008 attorney general',
    race_code == 'g08_ad' ~ '2008 auditor',
    race_code == 'g08_ca' ~ '2008 agriculture commissioner',
    race_code == 'g08_ci' ~ '2008 insurance commissioner',
    race_code == 'g08_cl' ~ '2008 labor commissioner',
    race_code == 'g10_uss' ~ '2010 U.S. Senate',
    race_code == 'g12_pr' ~ '2012 president',
    race_code == 'g12_gv' ~ '2012 governor',
    race_code == 'g12_lg' ~ '2012 lieutenant governor',
    race_code == 'g12_sst' ~ '2012 secretary of state',
    race_code == 'g12_ci' ~ '2012 insurance commissioner',
    race_code == 'g14_uss' ~ '2014 U.S. Senate',
    race_code == 'g16_pr' ~ '2016 president',
    race_code == 'g16_gv' ~ '2016 governor',
    race_code == 'g16_lg' ~ '2016 lieutenant governor',
    race_code == 'g16_uss' ~ '2016 U.S. Senate',
    race_code == 'g16_ag' ~ '2016 attorney general',
    race_code == 'g20_pr' ~ '2020 president',
    race_code == 'g20_uss' ~ '2020 U.S. Senate',
    race_code == 'g20_gv' ~ '2020 governor',
    race_code == 'g20_lg' ~ '2020 lieutenant governor',
    race_code == 'g20_ag' ~ '2020 attorney general',
    race_code == 'g20_ca' ~ '2020 agriculture commissioner',
    race_code == 'g20_tr' ~ '2020 treasurer',
    race_code == 'g20_ad' ~ '2020 auditor',
    race_code == 'g20_sst' ~ '2020 secretary of state',
    race_code == 'g20_ci' ~ '2020 insurance commissioner',
    race_code == 'g20_cl' ~ '2020 labor commissioner'
  )
  
  return(parsed_race_code)
}

# function to generate a table of election results for a given map using
# a provided block assignment file, year and race
#
# usage
# baf_nc_house22 %>%
#   genMapResult('nc_house', 'g20_pr')
genMapResult <- function(baf, chamber, race_code, crosswalk = duke_crosswalk){
  
  #get the ideal population for given chamber
  ideal_pop <- case_when(
    chamber == 'nc_house'~ 10439388/120,
    chamber == 'nc_senate' ~ 10439388/50,
    chamber == 'us_house' ~ 10439388/14,
    .default = 0
  )
  #check for valid entry
  if(ideal_pop == 0){
    cat('X...Error: invalid chamber_code entered')
    break
  }
  
  #narrow down the elections table to the specific race and year
  election_table <- crosswalk %>% 
    select(geo_id, pop2020cen, 
           imputed_votes_dem = paste0(race_code,'_d'),
           imputed_votes_rep = paste0(race_code, '_r'),
           bvap2020cen = bvap2020ce,
           vap2020cen) %>% 
    mutate(imputed_votes_total = imputed_votes_dem + imputed_votes_rep, .after = imputed_votes_rep)
  
  baf %>% 
    left_join(election_table, by = c('block' = 'geo_id')) %>% 
    group_by(district) %>% 
    summarize(population = sum(pop2020cen),
              pop_dev = sum(pop2020cen) - ideal_pop,
              pop_dev_pct = round( ((sum(pop2020cen) - ideal_pop) / ideal_pop) * 100, 2),
              bvap_pct = round( sum(bvap2020cen) / sum(vap2020cen) * 100, 1) ,
              dem_votes = sum(imputed_votes_dem),
              total_votes = sum(imputed_votes_total),
              dem_pct = round( sum(imputed_votes_dem) / (sum(imputed_votes_dem) + sum(imputed_votes_rep) ) * 100 , 1 ),
              party_win = ifelse(sum(imputed_votes_dem) > sum(imputed_votes_rep), 'D', 'R') )
}

# function to generate election tables for an entire list of contests
# showing number of democrats elected
#
# usage
# baf_nc_house22 %>% genElectionTables('nc_house', c('g20_pr', 'g16_pr', 'g12_pr', 'g08_pr'))
genElectionTables <- function(baf, chamber, contest_list, crosswalk = duke_crosswalk){
  
  #get the majority count for given chamber
  majority <- case_when(
    chamber == 'nc_house'~ 120/2 + 1,
    chamber == 'nc_senate' ~ 50/2 + 1,
    chamber == 'us_house' ~ NA,
    .default = 0
  )
  #supermajority
  supermajority <- case_when(
    chamber == 'nc_house'~ 120 * 3/5,
    chamber == 'nc_senate' ~ 50 * 3/5,
    chamber == 'us_house' ~ NA,
    .default = 0
  )

  #initialize an empty ist
  data_list = list()
  
  #loop through the list of contests
  for (i in contest_list){
    race_code = i
    #get the map result for the given contest
    map_result <- baf %>%
      genMapResult(chamber, race_code, crosswalk)
    
    #tally up the seats total vote percentages
    map_summary <- map_result %>%
      arrange(desc(dem_pct)) %>% 
      summarize(
       seats = sum(party_win == 'D'),
       total_dem_votes = sum(dem_votes),
       total_dr_votes = sum(total_votes),
       swing_majority = ifelse(is.na(majority), NA, 50 - nth(dem_pct, majority) ),
       swing_supermajority = ifelse(is.na(supermajority), NA, 50 - nth(dem_pct, supermajority) ),
      ) %>% 
      mutate(dem_pct = round(total_dem_votes/total_dr_votes * 100, 2)) %>% 
      mutate(race_code = race_code, .before = everything())
    
    #assign the contest to a list
    data_list[[race_code]] <- map_summary
    
  }
  
  #collapse the list of contest results to a single dataframe
  election_tables <- data_list %>% 
    bind_rows()
  
  #return the total list of contests
  return(election_tables)

}

# function to tally up number of dems elected across ensemble
# uses path to raw distribution files downloaded from duke team or a preloaded dataframe:
# https://git.math.duke.edu/gitlab/gjh/redistricting2020results/-/tree/main/NC/Ensembles
# also accepts upper and lower boundaries to construct table
#
# usage
# genHistogramData('../data/ensembles/house/mcd_on/statewide_G20_PR.csv', 45, 65)
genHistogramData <- function(ensemble_data, hist_start, hist_end){
  
  #check for dataframe and read in file if its a path
  if(!is.data.frame(ensemble_data)){
    ensemble_data <- read_csv(ensemble_data, show_col_types = FALSE)
  }
  
  #generate a single-column dataframe using provided boundaries
  data.frame(dems_elected = c(hist_start:hist_end)) %>% 
    #join with the raw distribution file after processing
    left_join(
      ensemble_data %>%
        #calculate the number of dems elected by counting vote totals above 50%
        mutate(dems_elected = rowSums(. > 0.5)) %>% 
        select(dems_elected) %>%
        #group by the number of dems elected to get the distribution across all maps
        count(dems_elected, name = 'map_count'),
      by = 'dems_elected'
    ) %>%
    #replace any nulls with zero
    replace_na(list(map_count = 0) ) %>%
    #reformat the percentages
    mutate(hist_pct = round(map_count/100000 * 100, 1) )
}

# function to generate a table of most common values from a list of contests
#
# usage
# genEnsembleModes(all_contests, '../data/ensembles/house/mcd_on/statewide_')
genEnsembleModes <- function(contest_list, ensemble_base_path){
  
  #intialize an empty table
  ensemble_modes <- tibble(
    race_code = character(),
    dems_elected = double(),
    map_count = integer(),
    hist_pct = double(),
  )
  
  #loop through the contest list and generate 
  for(contest in lapply(contest_list, toupper)){
    path <- paste0(ensemble_base_path, contest, '.csv')
    
    ensemble_modes <- ensemble_modes %>% 
      rbind(
        genHistogramData(path, 0, 120) %>% 
          filter(map_count == max(map_count)) %>% 
          mutate(race_code = tolower(contest), .before = everything())
      )
  }
  
  return(ensemble_modes)
  
}

# function to generate a dataframe of the number and percentage of matches in
# the ensemble for a given number of seats per election contest
# 
# usage
# baf_nc_house_h898 %>%
#   genElectionTables('nc_house', all_contests) %>%
#   genEnsembleMatches('../data/ensembles/house/mcd_on/statewide_')
genEnsembleMatches <- function(election_tables, ensemble_base_path){
  
  #intialize an empty table
  ensemble_matches <- tibble(
    race_code = character(),
    dems_elected = double(),
    map_count = integer(),
    hist_pct = double(),
  )
  
  #loop through the election tables and see how many ensembles match
  for(row in 1:nrow(election_tables)){
    #get the data from the election table row
    contest <- election_tables[row, 'race_code'][[1]]
    seats <- election_tables[row, 'seats'][[1]]
    
    #build the ensemble path
    path <- paste0(ensemble_base_path, contest, '.csv')
    
    ensemble_matches <- ensemble_matches %>% 
      rbind(
        genHistogramData(path, 0, 120) %>% 
          filter(dems_elected == seats) %>% 
          mutate(race_code = tolower(contest), .before = everything())
    )
  }
  
  return(ensemble_matches)
  
}

# function to produce a histogram using duke ensemble performance data
# and performance of a given map proposal. accepts a two-digit year,
# a race, and a preloaded block assignment file.
#
# usage
# genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_PR.csv', 'g20_pr', 'us_house', baf_us_house22)
genHistogramChart <- function(raw_file_path, race_code, chamber, baf, mcd = 1){
  
  #set the mcd status, default is on
  mcd_status <- ifelse(mcd == 1, 'on', 'off')
  
  #get the parsed race code for display
  parsed_race_code <- parseRaceCode(race_code)
  
  #parse the map proposal for display
  parsed_map_name <-toupper(str_replace_all(str_remove(deparse(substitute(baf)), 'baf_'), '_', ' '))
  
  hist_start <- case_when(
    chamber == 'nc_house' ~ 35,
    chamber == 'nc_senate' ~ 10,
    chamber == 'us_house' ~ 0,
    .default = NA
  )
  hist_end <- case_when(
    chamber == 'nc_house' ~ 75,
    chamber == 'nc_senate' ~ 35,
    chamber == 'us_house' ~ 14,
    .default = NA
  )
  #check for valid entry
  if(is.na(hist_start) | is.na(hist_end)){
    cat('X...Error: invalid chamber_code entered')
    break
  }
  
  seat_count <- baf %>%
    genMapResult(chamber, race_code) %>%
    summarize(seats = sum(party_win == 'D')) %>%
    pull(seats)
  
  #generate the source data
  genHistogramData(raw_file_path, hist_start, hist_end) %>% {
    #base plot data
    ggplot(., aes(dems_elected,
                  hist_pct,
                  yend = 60,
                  fill = ifelse( hist_pct == max(hist_pct), 'highlight', 'normal') )
    ) +
      geom_col() +
      #set annotation of mode value with a curved arrow
      annotate(
        geom = "curve",
        x = .[which(.$hist_pct == max(.$hist_pct)), "dems_elected"] + 5,
        y = max(.$hist_pct) + 10,
        xend = .[which(.$hist_pct == max(.$hist_pct)), "dems_elected"],
        yend = max(.$hist_pct) + 0.5, 
        curvature = .3, arrow = arrow(length = unit(2, "mm"))
      ) +
      #set annotation of mode value with label text
      annotate(geom = "text",
               x = .[which(.$hist_pct == max(.$hist_pct)), "dems_elected"] + 5.25,
               y = max(.$hist_pct) + 10,
               label = "most common result\nacross 100,000 maps",
               lineheight = 0.9,
               hjust = "left"
      ) +
      #generate point showing map proposal value for comparison
      geom_point( aes(x = seat_count,
                      y = 1),
                  color = '#fc8d62',
                  size = 3
      ) +
      #set annotation of proposal value with curved arrow
      annotate(
        geom = "curve",
        x = seat_count - 5,
        y = 9,
        xend = seat_count - 0.2,
        yend = 2.5, 
        curvature = -0.3, arrow = arrow(length = unit(2, "mm"))
      ) +
      #set annotation of proposal value with label text
      annotate(geom = "text",
               x = seat_count - 5.25,
               y = 9,
               label = "how this map\nperformed",
               lineheight = 0.9,
               hjust = "right"
      ) +
      #color the bars
      scale_fill_manual(values=c('gray40', 'gray80')) +
      #customize the breaks on the x axis
      scale_x_continuous(breaks = seq(from = hist_start, to = hist_end, by = 5),
                         minor_breaks = seq(from = hist_start, to = hist_end, by = 1)
      ) +
      #customize the y axis
      scale_y_continuous(breaks = seq(from = 0, to = 60, by = 10)) +
      #add labels based on inputs
      labs(
        x = '# OF DEMOCRATS ELECTED', y = '% OF MAPS WITH RESULT',
        title = paste0('How the maps performed: ', parsed_map_name),
        subtitle = paste0(parsed_race_code, ' | Respect city boundaries: ', toupper(mcd_status)),
        caption = 'SOURCE: Duke Quantifying Gerrymandering team, N&O analysis'
      ) +
      theme_minimal() +
      theme(legend.position = "none")
  }
}

# Run a uniform swing analysis with a given interval
#
# usage
# genSwingVotes(baf_nc_senate21, 'nc_senate', 'g20_pr', 0.005, 0.05)
genSwingVotes <- function(baf, chamber, race_code, interval, max_swing, crosswalk = duke_crosswalk){
  
  #create a vector of swing values to adjust votes by
  swing_values <- seq(from = interval, to = max_swing, by = interval)
  
  #establish d and r col
  d_col = paste0(race_code, '_d')
  r_col = paste0(race_code, '_r')
  
  #construct a new crosswalk using the swing values
  swing_crosswalk <- crosswalk %>% 
    select(geo_id:pop2020cen, vap2020cen, bvap2020ce,
           !!d_col, !!r_col )
  
  swing_crosswalk <- swing_crosswalk %>% 
    mutate(total_dr = !!as.name(d_col) + !!as.name(r_col) )
  
  for(value in swing_values){
    swing_crosswalk <- swing_crosswalk %>% 
      mutate('{race_code}_{value}_d' := !!as.name(d_col) + total_dr * value,
             '{race_code}_{value}_r' := !!as.name(r_col) - total_dr * value)
  }
  
  #use swing values to create vector of contest list race codes
  contest_list <- append(race_code, paste0(race_code, '_', swing_values) )
  
  #generate the election tables
  genElectionTables(baf, chamber, contest_list, crosswalk = swing_crosswalk )
  
}

# Use uniform swing analysis to generate a table of most common values from 
# the Duke ensemble for a given interval and max swing.
#
# usage
# genEnsembleSwing('../data/ensembles/house/mcd_on/statewide_G20_PR.csv', 'g20_pr', 0.005, 0.05)
genEnsembleSwing <- function(ensemble_data_path, race_code, interval, max_swing){
  
  #create a vector of swing values to adjust votes by
  swing_values <- seq(from = interval, to = max_swing, by = interval)
  
  #initialize the simplified histogram data
  base_election <- read_csv(ensemble_data_path, show_col_types = FALSE)
  
  histogram_data <- base_election %>% 
    genHistogramData(0, 120) %>%
    filter(map_count == max(map_count)) %>% 
    mutate(race_code = race_code, .before = everything())
  
  #loop through the vector of swing values to add to the histogram data
  for(value in swing_values){
    swing_election <- base_election %>% 
      mutate(across(everything(), ~ .x + value)) %>% 
      genHistogramData(0, 120) %>%
      filter(map_count == max(map_count)) %>% 
      mutate(race_code = paste0(race_code, '_', value), .before = everything())
    
    histogram_data <- histogram_data %>% 
      rbind(swing_election)
  }
  
  histogram_data <- histogram_data %>% 
    rename(hist_mode_dems = dems_elected, hist_count = map_count)
  
  return(histogram_data)
  
}

# utility function to convert swing data to json
genSwingJSON <- function(swing_data){
  
  #initialize an emtpy list
  swing_list <- list()
  
  #iterate through the swing data to reformat the list
  for(row in 1:nrow(swing_data)){
    list_item <- list(list(democrats = swing_data[row, 'democrats'][[1]],
                           republicans = swing_data[row, 'republicans'][[1]]))
    swing_list[as.character(swing_data[row, 'dem_pct'][[1]])] <- list_item
  }
  
  swing_json <- swing_list %>% 
    toJSON(auto_unbox = TRUE, pretty = TRUE )
  
  return(swing_json)
  
}

# utility function to convert histogram data to json
genHistogramJSON <- function(histogram_data){
  histogram_json <- setNames(as.list(histogram_data$map_count),
           as.list(histogram_data$dems_elected)
           ) %>%
    toJSON(auto_unbox = TRUE, pretty = TRUE )
  
  return(histogram_json)
}

# Generate final tables for full findings ---------------------------------

# NC HOUSE - H898
nc_house_table <- baf_nc_house_h898 %>%                                               # <- CHANGE baf HERE
  genElectionTables('nc_house', all_contests) %>%                                     # <- CHANGE chamber HERE
  select(race_code, dem_pct, dems_2023 = seats) %>% 
  left_join(
    baf_nc_house22 %>%                                                                # <- CHANGE baf HERE
      genElectionTables('nc_house', all_contests) %>%                                 # <- CHANGE chamber HERE
      select(race_code, dems_2022 = seats),
    by = 'race_code'
  ) %>%
  left_join(
    genEnsembleModes(all_contests, '../data/ensembles/house/mcd_on/statewide_') %>%   # <- CHANGE ensemble path HERE
      select(race_code, ensemble_mode = dems_elected, mode_pct = hist_pct),
    by = 'race_code'
  ) %>%
  left_join(
    baf_nc_house_h898 %>%                                                             # <- CHANGE baf HERE
      genElectionTables('nc_house', all_contests) %>%                                 # <- CHANGE chamber HERE
      genEnsembleMatches('../data/ensembles/house/mcd_on/statewide_') %>%             # <- CHANGE ensemble path HERE
      select(race_code, map_count, hist_pct),
    by = 'race_code'
  ) %>% 
  mutate(race_code_parsed = parseRaceCode(race_code),
         diff_2022 = dems_2023 - dems_2022,
         diff_ensemble = dems_2023 - ensemble_mode)

# NC SENATE - S758
nc_senate_table <- baf_nc_senate_s758 %>%                                              # <- CHANGE baf HERE
  genElectionTables('nc_senate', all_contests) %>%                                     # <- CHANGE chamber HERE
  select(race_code, dem_pct, dems_2023 = seats) %>% 
  left_join(
    baf_nc_senate22 %>%                                                                # <- CHANGE baf HERE
      genElectionTables('nc_senate', all_contests) %>%                                 # <- CHANGE chamber HERE
      select(race_code, dems_2022 = seats),
    by = 'race_code'
  ) %>%
  left_join(
    genEnsembleModes(all_contests, '../data/ensembles/senate/mcd_on/statewide_') %>%   # <- CHANGE ensemble path HERE
      select(race_code, ensemble_mode = dems_elected, mode_pct = hist_pct),
    by = 'race_code'
  ) %>%
  left_join(
    baf_nc_senate_s758 %>%                                                             # <- CHANGE baf HERE
      genElectionTables('nc_senate', all_contests) %>%                                 # <- CHANGE chamber HERE
      genEnsembleMatches('../data/ensembles/senate/mcd_on/statewide_') %>%             # <- CHANGE ensemble path HERE
      select(race_code, map_count, hist_pct),
    by = 'race_code'
  ) %>% 
  mutate(race_code_parsed = parseRaceCode(race_code),
         diff_2022 = dems_2023 - dems_2022,
         diff_ensemble = dems_2023 - ensemble_mode)

# US HOUSE - S756
us_house756_table <- baf_us_house_s756 %>%                                                               # <- CHANGE baf HERE
  genElectionTables('us_house', all_contests) %>%                                                        # <- CHANGE chamber HERE
  select(race_code, dem_pct, dems_2023 = seats) %>% 
  left_join(
    baf_us_house22 %>%                                                                                   # <- CHANGE baf HERE
      genElectionTables('us_house', all_contests) %>%                                                    # <- CHANGE chamber HERE
      select(race_code, dems_2022 = seats),
    by = 'race_code'
  ) %>%
  left_join(
    genEnsembleModes(all_contests, '../data/ensembles/congressional/atlas_measureID12_marginals_') %>%   # <- CHANGE ensemble path HERE
      select(race_code, ensemble_mode = dems_elected, mode_pct = hist_pct),
    by = 'race_code'
  ) %>%
  left_join(
    baf_us_house_s756 %>%                                                                                # <- CHANGE baf HERE
      genElectionTables('us_house', all_contests) %>%                                                    # <- CHANGE chamber HERE
      genEnsembleMatches('../data/ensembles/congressional/atlas_measureID12_marginals_') %>%             # <- CHANGE ensemble path HERE
      select(race_code, map_count, hist_pct),
    by = 'race_code'
  ) %>% 
  mutate(race_code_parsed = parseRaceCode(race_code),
         diff_2022 = dems_2023 - dems_2022,
         diff_ensemble = dems_2023 - ensemble_mode)

# US HOUSE - S757
us_house757_table <- baf_us_house_s757 %>%                                                               # <- CHANGE baf HERE
  genElectionTables('us_house', all_contests) %>%                                                        # <- CHANGE chamber HERE
  select(race_code, dem_pct, dems_2023 = seats) %>% 
  left_join(
    baf_us_house22 %>%                                                                                   # <- CHANGE baf HERE
      genElectionTables('us_house', all_contests) %>%                                                    # <- CHANGE chamber HERE
      select(race_code, dems_2022 = seats),
    by = 'race_code'
  ) %>%
  left_join(
    genEnsembleModes(all_contests, '../data/ensembles/congressional/atlas_measureID12_marginals_') %>%   # <- CHANGE ensemble path HERE
      select(race_code, ensemble_mode = dems_elected, mode_pct = hist_pct),
    by = 'race_code'
  ) %>%
  left_join(
    baf_us_house_s757 %>%                                                                                # <- CHANGE baf HERE
      genElectionTables('us_house', all_contests) %>%                                                    # <- CHANGE chamber HERE
      genEnsembleMatches('../data/ensembles/congressional/atlas_measureID12_marginals_') %>%             # <- CHANGE ensemble path HERE
      select(race_code, map_count, hist_pct),
    by = 'race_code'
  ) %>% 
  mutate(race_code_parsed = parseRaceCode(race_code),
         diff_2022 = dems_2023 - dems_2022,
         diff_ensemble = dems_2023 - ensemble_mode)


# Rerunning final tables for enacted maps ---------------------------------

# NC HOUSE - H898 - 3RD EDITION, ENACTED
nc_house_table <- baf_nc_house_h898_ed3 %>%                                               # <- CHANGE baf HERE
  genElectionTables('nc_house', all_contests) %>%                                         # <- CHANGE chamber HERE
  select(race_code, dem_pct, dems_2023_enacted = seats) %>% 
  left_join(
    baf_nc_house_h898 %>%                                                                 # <- CHANGE baf HERE
      genElectionTables('nc_house', all_contests) %>%                                     # <- CHANGE chamber HERE
      select(race_code, dems_2023_filed = seats),
    by = 'race_code'
  ) %>%
  left_join(
    baf_nc_house22 %>%                                                                    # <- CHANGE baf HERE
      genElectionTables('nc_house', all_contests) %>%                                     # <- CHANGE chamber HERE
      select(race_code, dems_2022 = seats),
    by = 'race_code'
  ) %>%
  left_join(
    genEnsembleModes(all_contests, '../data/ensembles/house/mcd_on/statewide_') %>%       # <- CHANGE ensemble path HERE
      select(race_code, ensemble_mode = dems_elected, mode_pct = hist_pct),
    by = 'race_code'
  ) %>%
  left_join(
    baf_nc_house_h898_ed3 %>%                                                             # <- CHANGE baf HERE
      genElectionTables('nc_house', all_contests) %>%                                     # <- CHANGE chamber HERE
      genEnsembleMatches('../data/ensembles/house/mcd_on/statewide_') %>%                 # <- CHANGE ensemble path HERE
      select(race_code, map_count, hist_pct),
    by = 'race_code'
  ) %>% 
  mutate(race_code_parsed = parseRaceCode(race_code),
         diff_enacted = dems_2023_enacted - dems_2023_filed,
         diff_2022 = dems_2023_enacted - dems_2022,
         diff_ensemble = dems_2023_enacted - ensemble_mode)


# NC SENATE - S758 - 3RD EDITION, ENACTED
nc_senate_table <- baf_nc_senate_s758_ed2 %>%                                              # <- CHANGE baf HERE
  genElectionTables('nc_senate', all_contests) %>%                                         # <- CHANGE chamber HERE
  select(race_code, dem_pct, dems_2023_enacted = seats) %>%
  left_join(
    baf_nc_senate_s758 %>%                                                                 # <- CHANGE baf HERE
      genElectionTables('nc_senate', all_contests) %>%                                     # <- CHANGE chamber HERE
      select(race_code, dems_2023_filed = seats),
    by = 'race_code'
  ) %>%
  left_join(
    baf_nc_senate22 %>%                                                                    # <- CHANGE baf HERE
      genElectionTables('nc_senate', all_contests) %>%                                     # <- CHANGE chamber HERE
      select(race_code, dems_2022 = seats),
    by = 'race_code'
  ) %>%
  left_join(
    genEnsembleModes(all_contests, '../data/ensembles/senate/mcd_on/statewide_') %>%       # <- CHANGE ensemble path HERE
      select(race_code, ensemble_mode = dems_elected, mode_pct = hist_pct),
    by = 'race_code'
  ) %>%
  left_join(
    baf_nc_senate_s758_ed2 %>%                                                             # <- CHANGE baf HERE
      genElectionTables('nc_senate', all_contests) %>%                                     # <- CHANGE chamber HERE
      genEnsembleMatches('../data/ensembles/senate/mcd_on/statewide_') %>%                # <- CHANGE ensemble path HERE
      select(race_code, map_count, hist_pct),
    by = 'race_code'
  ) %>% 
  mutate(race_code_parsed = parseRaceCode(race_code),
         diff_enacted = dems_2023_enacted - dems_2023_filed,
         diff_2022 = dems_2023_enacted - dems_2022,
         diff_ensemble = dems_2023_enacted - ensemble_mode)

# US HOUSE - S757 - 2ND EDITION, ENACTED
us_house757_table <- baf_us_house_s757_ed2 %>%                                                               # <- CHANGE baf HERE
  genElectionTables('us_house', all_contests) %>%                                                            # <- CHANGE chamber HERE
  select(race_code, dem_pct, dems_2023_enacted = seats) %>%
  left_join(
    baf_us_house_s757 %>%                                                                                    # <- CHANGE baf HERE
      genElectionTables('us_house', all_contests) %>%                                                        # <- CHANGE chamber HERE
      select(race_code, dems_2023_filed = seats),
    by = 'race_code'
  ) %>%
  left_join(
    baf_us_house22 %>%                                                                                       # <- CHANGE baf HERE
      genElectionTables('us_house', all_contests) %>%                                                        # <- CHANGE chamber HERE
      select(race_code, dems_2022 = seats),
    by = 'race_code'
  ) %>%
  left_join(
    genEnsembleModes(all_contests, '../data/ensembles/congressional/atlas_measureID12_marginals_') %>%      # <- CHANGE ensemble path HERE
      select(race_code, ensemble_mode = dems_elected, mode_pct = hist_pct),
    by = 'race_code'
  ) %>%
  left_join(
    baf_us_house_s757_ed2 %>%                                                                                # <- CHANGE baf HERE
      genElectionTables('us_house', all_contests) %>%                                                        # <- CHANGE chamber HERE
      genEnsembleMatches('../data/ensembles/congressional/atlas_measureID12_marginals_') %>%                 # <- CHANGE ensemble path HERE
      select(race_code, map_count, hist_pct),
    by = 'race_code'
  ) %>% 
  mutate(race_code_parsed = parseRaceCode(race_code),
         diff_enacted = dems_2023_enacted - dems_2023_filed,
         diff_2022 = dems_2023_enacted - dems_2022,
         diff_ensemble = dems_2023_enacted - ensemble_mode)

# Run uniform swing analysis ----------------------------------------------

# NC HOUSE - H898
# 2020 president
nc_house_swing_g20_pr <- genSwingVotes(baf_nc_house_h898, 'nc_house', 'g20_pr', 0.005, 0.05) %>%     # <- CHANGE baf, chamber, race_code HERE
  select(race_code, dem_pct, dems_2023 = seats, 
         swg_maj2023 = swing_majority, swg_supermaj_2023 = swing_supermajority) %>% 
  left_join(
    genSwingVotes(baf_nc_house21, 'nc_house', 'g20_pr', 0.005, 0.05) %>%                             # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2021 = seats, 
             swg_maj2021 = swing_majority, swg_supermaj_2021 = swing_supermajority),
    by = 'race_code'
  ) %>%
  left_join(
    genSwingVotes(baf_nc_house22, 'nc_house', 'g20_pr', 0.005, 0.05) %>%                             # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2022 = seats, 
             swg_maj2022 = swing_majority, swg_supermaj_2022 = swing_supermajority),
    by = 'race_code'
  ) %>%
  left_join(
    genEnsembleSwing('../data/ensembles/house/mcd_on/statewide_G20_PR.csv', 'g20_pr', 0.005, 0.05), # <- CHANGE ensemble, race_code HERE
    by = 'race_code'
  ) %>%
  mutate(swing_value = if_else(is.na(str_extract(race_code,'^.+_.+_(.+)$', 1)), 
                               0, 
                               parse_double(str_extract(race_code,'^.+_.+_(.+)$', 1)) * 100))

# 2020 governor
nc_house_swing_g20_gv <- genSwingVotes(baf_nc_house_h898, 'nc_house', 'g20_gv', 0.005, 0.05) %>%     # <- CHANGE baf, chamber, race_code HERE
  select(race_code, dem_pct, dems_2023 = seats, 
         swg_maj2023 = swing_majority, swg_supermaj_2023 = swing_supermajority) %>% 
  left_join(
    genSwingVotes(baf_nc_house21, 'nc_house', 'g20_gv', 0.005, 0.05) %>%                             # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2021 = seats, 
             swg_maj2021 = swing_majority, swg_supermaj_2021 = swing_supermajority),
    by = 'race_code'
  ) %>%
  left_join(
    genSwingVotes(baf_nc_house22, 'nc_house', 'g20_gv', 0.005, 0.05) %>%                             # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2022 = seats, 
             swg_maj2022 = swing_majority, swg_supermaj_2022 = swing_supermajority),
    by = 'race_code'
  ) %>%
  left_join(
    genEnsembleSwing('../data/ensembles/house/mcd_on/statewide_G20_GV.csv', 'g20_gv', 0.005, 0.05), # <- CHANGE ensemble, race_code HERE
    by = 'race_code'
  ) %>%
  mutate(swing_value = if_else(is.na(str_extract(race_code,'^.+_.+_(.+)$', 1)), 
                               0, 
                               parse_double(str_extract(race_code,'^.+_.+_(.+)$', 1)) * 100))

# NC SENATE - S758
# 2020 president
nc_senate_swing_g20_pr <- genSwingVotes(baf_nc_senate_s758, 'nc_senate', 'g20_pr', 0.005, 0.05) %>%     # <- CHANGE baf, chamber, race_code HERE
  select(race_code, dem_pct, dems_2023 = seats, 
         swg_maj2023 = swing_majority, swg_supermaj_2023 = swing_supermajority) %>% 
  left_join(
    genSwingVotes(baf_nc_senate21, 'nc_senate', 'g20_pr', 0.005, 0.05) %>%                             # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2021 = seats, 
             swg_maj2021 = swing_majority, swg_supermaj_2021 = swing_supermajority),
    by = 'race_code'
  ) %>%
  left_join(
    genSwingVotes(baf_nc_senate22, 'nc_senate', 'g20_pr', 0.005, 0.05) %>%                             # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2022 = seats, 
             swg_maj2022 = swing_majority, swg_supermaj_2022 = swing_supermajority),
    by = 'race_code'
  ) %>%
  left_join(
    genEnsembleSwing('../data/ensembles/senate/mcd_on/statewide_G20_PR.csv', 'g20_pr', 0.005, 0.05),    # <- CHANGE ensemble HERE
    by = 'race_code'
  ) %>%
  mutate(swing_value = if_else(is.na(str_extract(race_code,'^.+_.+_(.+)$', 1)), 
                               0, 
                               parse_double(str_extract(race_code,'^.+_.+_(.+)$', 1)) * 100))

# 2020 governor
nc_senate_swing_g20_gv <- genSwingVotes(baf_nc_senate_s758, 'nc_senate', 'g20_gv', 0.005, 0.05) %>%     # <- CHANGE baf, chamber, race_code HERE
  select(race_code, dem_pct, dems_2023 = seats, 
         swg_maj2023 = swing_majority, swg_supermaj_2023 = swing_supermajority) %>% 
  left_join(
    genSwingVotes(baf_nc_senate21, 'nc_senate', 'g20_gv', 0.005, 0.05) %>%                             # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2021 = seats, 
             swg_maj2021 = swing_majority, swg_supermaj_2021 = swing_supermajority),
    by = 'race_code'
  ) %>%
  left_join(
    genSwingVotes(baf_nc_senate22, 'nc_senate', 'g20_gv', 0.005, 0.05) %>%                             # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2022 = seats, 
             swg_maj2022 = swing_majority, swg_supermaj_2022 = swing_supermajority),
    by = 'race_code'
  ) %>%
  left_join(
    genEnsembleSwing('../data/ensembles/senate/mcd_on/statewide_G20_GV.csv', 'g20_gv', 0.005, 0.05),    # <- CHANGE ensemble HERE
    by = 'race_code'
  ) %>%
  mutate(swing_value = if_else(is.na(str_extract(race_code,'^.+_.+_(.+)$', 1)), 
                               0, 
                               parse_double(str_extract(race_code,'^.+_.+_(.+)$', 1)) * 100))

# Rerun uniform swing analysis for enacted maps ---------------------------

# NC HOUSE - H898
# 2020 president
nc_house_swing_g20_pr <- genSwingVotes(baf_nc_house_h898_ed3, 'nc_house', 'g20_pr', 0.005, 0.05) %>%     # <- CHANGE baf, chamber, race_code HERE
  select(race_code, dem_pct, dems_2023_enacted = seats, 
         swg_maj2023_enacted = swing_majority, swg_supermaj_2023_enacted = swing_supermajority) %>%
  left_join(
    genSwingVotes(baf_nc_house_h898, 'nc_house', 'g20_pr', 0.005, 0.05) %>%                              # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2023_filed = seats, 
             swg_maj2023_filed = swing_majority, swg_supermaj_2023_filed = swing_supermajority),
    by = 'race_code'
  ) %>% 
  left_join(
    genSwingVotes(baf_nc_house21, 'nc_house', 'g20_pr', 0.005, 0.05) %>%                                 # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2021 = seats, 
             swg_maj2021 = swing_majority, swg_supermaj_2021 = swing_supermajority),
    by = 'race_code'
  ) %>%
  left_join(
    genSwingVotes(baf_nc_house22, 'nc_house', 'g20_pr', 0.005, 0.05) %>%                                 # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2022 = seats, 
             swg_maj2022 = swing_majority, swg_supermaj_2022 = swing_supermajority),
    by = 'race_code'
  ) %>%
  left_join(
    genEnsembleSwing('../data/ensembles/house/mcd_on/statewide_G20_PR.csv', 'g20_pr', 0.005, 0.05),      # <- CHANGE ensemble, race_code HERE
    by = 'race_code'
  ) %>%
  mutate(swing_value = if_else(is.na(str_extract(race_code,'^.+_.+_(.+)$', 1)), 
                               0, 
                               parse_double(str_extract(race_code,'^.+_.+_(.+)$', 1)) * 100))

# 2020 governor
nc_house_swing_g20_gv <- genSwingVotes(baf_nc_house_h898_ed3, 'nc_house', 'g20_gv', 0.005, 0.05) %>%     # <- CHANGE baf, chamber, race_code HERE
  select(race_code, dem_pct, dems_2023_enacted = seats, 
         swg_maj2023_enacted = swing_majority, swg_supermaj_2023_enacted = swing_supermajority) %>%
  left_join(
    genSwingVotes(baf_nc_house_h898, 'nc_house', 'g20_gv', 0.005, 0.05) %>%                              # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2023_filed = seats, 
             swg_maj2023_filed = swing_majority, swg_supermaj_2023_filed = swing_supermajority),
    by = 'race_code'
  ) %>% 
  left_join(
    genSwingVotes(baf_nc_house21, 'nc_house', 'g20_gv', 0.005, 0.05) %>%                                 # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2021 = seats, 
             swg_maj2021 = swing_majority, swg_supermaj_2021 = swing_supermajority),
    by = 'race_code'
  ) %>%
  left_join(
    genSwingVotes(baf_nc_house22, 'nc_house', 'g20_gv', 0.005, 0.05) %>%                                 # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2022 = seats, 
             swg_maj2022 = swing_majority, swg_supermaj_2022 = swing_supermajority),
    by = 'race_code'
  ) %>%
  left_join(
    genEnsembleSwing('../data/ensembles/house/mcd_on/statewide_G20_GV.csv', 'g20_gv', 0.005, 0.05),      # <- CHANGE ensemble, race_code HERE
    by = 'race_code'
  ) %>%
  mutate(swing_value = if_else(is.na(str_extract(race_code,'^.+_.+_(.+)$', 1)), 
                               0, 
                               parse_double(str_extract(race_code,'^.+_.+_(.+)$', 1)) * 100))
  
# NC SENATE - S758
# 2020 president
nc_senate_swing_g20_pr <- genSwingVotes(baf_nc_senate_s758_ed2, 'nc_senate', 'g20_pr', 0.005, 0.05) %>%     # <- CHANGE baf, chamber, race_code HERE
  select(race_code, dem_pct, dems_2023_enacted = seats, 
         swg_maj2023_enacted = swing_majority, swg_supermaj_2023_enacted = swing_supermajority) %>%
  left_join(
    genSwingVotes(baf_nc_senate_s758, 'nc_senate', 'g20_pr', 0.005, 0.05) %>%                               # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2023_filed = seats, 
             swg_maj2023_filed = swing_majority, swg_supermaj_2023_filed = swing_supermajority),
    by = 'race_code'
  ) %>%
  left_join(
    genSwingVotes(baf_nc_senate21, 'nc_senate', 'g20_pr', 0.005, 0.05) %>%                                  # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2021 = seats, 
             swg_maj2021 = swing_majority, swg_supermaj_2021 = swing_supermajority),
    by = 'race_code'
  ) %>%
  left_join(
    genSwingVotes(baf_nc_senate22, 'nc_senate', 'g20_pr', 0.005, 0.05) %>%                                  # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2022 = seats, 
             swg_maj2022 = swing_majority, swg_supermaj_2022 = swing_supermajority),
    by = 'race_code'
  ) %>%
  left_join(
    genEnsembleSwing('../data/ensembles/senate/mcd_on/statewide_G20_PR.csv', 'g20_pr', 0.005, 0.05),        # <- CHANGE ensemble HERE
    by = 'race_code'
  ) %>%
  mutate(swing_value = if_else(is.na(str_extract(race_code,'^.+_.+_(.+)$', 1)), 
                               0, 
                               parse_double(str_extract(race_code,'^.+_.+_(.+)$', 1)) * 100))

# 2020 governor
nc_senate_swing_g20_gv <- genSwingVotes(baf_nc_senate_s758_ed2, 'nc_senate', 'g20_gv', 0.005, 0.05) %>%     # <- CHANGE baf, chamber, race_code HERE
  select(race_code, dem_pct, dems_2023_enacted = seats, 
         swg_maj2023_enacted = swing_majority, swg_supermaj_2023_enacted = swing_supermajority) %>%
  left_join(
    genSwingVotes(baf_nc_senate_s758, 'nc_senate', 'g20_gv', 0.005, 0.05) %>%                               # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2023_filed = seats, 
             swg_maj2023_filed = swing_majority, swg_supermaj_2023_filed = swing_supermajority),
    by = 'race_code'
  ) %>% 
  left_join(
    genSwingVotes(baf_nc_senate21, 'nc_senate', 'g20_gv', 0.005, 0.05) %>%                                  # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2021 = seats, 
             swg_maj2021 = swing_majority, swg_supermaj_2021 = swing_supermajority),
    by = 'race_code'
  ) %>%
  left_join(
    genSwingVotes(baf_nc_senate22, 'nc_senate', 'g20_gv', 0.005, 0.05) %>%                                  # <- CHANGE baf, chamber, race_code HERE
      select(race_code, dems_2022 = seats, 
             swg_maj2022 = swing_majority, swg_supermaj_2022 = swing_supermajority),
    by = 'race_code'
  ) %>%
  left_join(
    genEnsembleSwing('../data/ensembles/senate/mcd_on/statewide_G20_GV.csv', 'g20_gv', 0.005, 0.05),        # <- CHANGE ensemble HERE
    by = 'race_code'
    ) %>%
  mutate(swing_value = if_else(is.na(str_extract(race_code,'^.+_.+_(.+)$', 1)), 
                               0, 
                               parse_double(str_extract(race_code,'^.+_.+_(.+)$', 1)) * 100))
  

# Fact checking -----------------------------------------------------------

#check the breakdown for major 2020 races
nc_house_table %>% filter(race_code %in% c('g20_pr', 'g20_uss', 'g20_gv', 'g20_lg', 'g20_ag'))

nc_senate_table %>% filter(race_code %in% c('g20_pr', 'g20_uss', 'g20_gv', 'g20_lg', 'g20_ag'))

us_house757_table %>% filter(race_code %in% c('g20_pr', 'g20_uss', 'g20_gv', 'g20_lg', 'g20_ag'))

#NOT ENACTED
us_house756_table %>% filter(race_code %in% c('g20_pr', 'g20_uss', 'g20_gv', 'g20_lg', 'g20_ag'))

#quickly find the swing values for the majority for the proposed maps
nc_house_swing_g20_pr %>% 
  filter(race_code == 'g20_pr') %>% 
  select(swg_maj2023_enacted)

nc_house_swing_g20_gv %>% 
  filter(race_code == 'g20_gv') %>% 
  select(swg_maj2023_enacted)

nc_senate_swing_g20_pr %>% 
  filter(race_code == 'g20_pr') %>% 
  select(swg_maj2023_enacted)

nc_senate_swing_g20_gv %>% 
  filter(race_code == 'g20_gv') %>% 
  select(swg_maj2023_enacted)

# Creating histogram graphics ---------------------------------------------

#NC HOUSE - H898
#create and save histograms to the repo
genHistogramChart('../data/ensembles/house/mcd_on/statewide_G20_PR.csv', 'g20_pr', 'nc_house', baf_nc_house_h898) %>%
  ggsave('../charts/nc_house_g20_pr.png', plot = ., bg = 'white')
genHistogramChart('../data/ensembles/house/mcd_on/statewide_G20_USS.csv', 'g20_uss', 'nc_house', baf_nc_house_h898) %>%
  ggsave('../charts/nc_house_g20_uss.png', plot = ., bg = 'white')
genHistogramChart('../data/ensembles/house/mcd_on/statewide_G20_GV.csv', 'g20_gv', 'nc_house', baf_nc_house_h898) %>%
  ggsave('../charts/nc_house_g20_gv.png', plot = ., bg = 'white')
genHistogramChart('../data/ensembles/house/mcd_on/statewide_G20_LG.csv', 'g20_lg', 'nc_house', baf_nc_house_h898) %>%
  ggsave('../charts/nc_house_g20_lg.png', plot = ., bg = 'white')
genHistogramChart('../data/ensembles/house/mcd_on/statewide_G20_AG.csv', 'g20_ag', 'nc_house', baf_nc_house_h898) %>%
  ggsave('../charts/nc_house_g20_ag.png', plot = ., bg = 'white')

#create and save a gif of the histograms to the repo
c('../charts/nc_house_g20_lg.png',
  '../charts/nc_house_g20_uss.png',
  '../charts/nc_house_g20_ag.png',
  '../charts/nc_house_g20_pr.png',
  '../charts/nc_house_g20_gv.png'
  ) %>% 
  lapply(., image_read) %>% 
  image_join() %>% 
  image_animate(fps = 0.5) %>% 
  image_write('../charts/gifs/nc_house_h898.gif')

# NC SENATE - S758
#create and save histograms to the repo
genHistogramChart('../data/ensembles/senate/mcd_on/statewide_G20_PR.csv', 'g20_pr', 'nc_senate', baf_nc_senate_s758) %>%
  ggsave('../charts/nc_senate_g20_pr.png', plot = ., bg = 'white')
genHistogramChart('../data/ensembles/senate/mcd_on/statewide_G20_USS.csv', 'g20_uss', 'nc_senate', baf_nc_senate_s758) %>%
  ggsave('../charts/nc_senate_g20_uss.png', plot = ., bg = 'white')
genHistogramChart('../data/ensembles/senate/mcd_on/statewide_G20_GV.csv', 'g20_gv', 'nc_senate', baf_nc_senate_s758) %>%
  ggsave('../charts/nc_senate_g20_gv.png', plot = ., bg = 'white')
genHistogramChart('../data/ensembles/senate/mcd_on/statewide_G20_LG.csv', 'g20_lg', 'nc_senate', baf_nc_senate_s758) %>%
  ggsave('../charts/nc_senate_g20_lg.png', plot = ., bg = 'white')
genHistogramChart('../data/ensembles/senate/mcd_on/statewide_G20_AG.csv', 'g20_ag', 'nc_senate', baf_nc_senate_s758) %>%
  ggsave('../charts/nc_senate_g20_ag.png', plot = ., bg = 'white')

#create and save a gif of the histograms to the repo
c('../charts/nc_senate_g20_lg.png',
  '../charts/nc_senate_g20_uss.png',
  '../charts/nc_senate_g20_pr.png',
  '../charts/nc_senate_g20_ag.png',
  '../charts/nc_senate_g20_gv.png'
) %>% 
  lapply(., image_read) %>% 
  image_join() %>% 
  image_animate(fps = 0.5) %>% 
  image_write('../charts/gifs/nc_senate_s758.gif')

# US HOUSE - S756
#create and save histograms to the repo
genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_PR.csv', 'g20_pr', 'us_house', baf_us_house_s756) %>%
  ggsave('../charts/us_house_s756_g20_pr.png', plot = ., bg = 'white')
genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_USS.csv', 'g20_uss', 'us_house', baf_us_house_s756) %>%
  ggsave('../charts/us_house_s756_g20_uss.png', plot = ., bg = 'white')
genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_GV.csv', 'g20_gv', 'us_house', baf_us_house_s756) %>%
  ggsave('../charts/us_house_s756_g20_gv.png', plot = ., bg = 'white')
genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_LG.csv', 'g20_lg', 'us_house', baf_us_house_s756) %>%
  ggsave('../charts/us_house_s756_g20_lg.png', plot = ., bg = 'white')
genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_AG.csv', 'g20_ag', 'us_house', baf_us_house_s756) %>%
  ggsave('../charts/us_house_s756_g20_ag.png', plot = ., bg = 'white')

#create and save a gif of the histograms to the repo
c('../charts/us_house_s756_g20_lg.png',
  '../charts/us_house_s756_g20_uss.png',
  '../charts/us_house_s756_g20_pr.png',
  '../charts/us_house_s756_g20_ag.png',
  '../charts/us_house_s756_g20_gv.png'
) %>% 
  lapply(., image_read) %>% 
  image_join() %>% 
  image_animate(fps = 0.5) %>% 
  image_write('../charts/gifs/us_house_s756.gif')

# US HOUSE - S757
#create and save histograms to the repo
genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_PR.csv', 'g20_pr', 'us_house', baf_us_house_s757) %>%
  ggsave('../charts/us_house_s757_g20_pr.png', plot = ., bg = 'white')
genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_USS.csv', 'g20_uss', 'us_house', baf_us_house_s757) %>%
  ggsave('../charts/us_house_s757_g20_uss.png', plot = ., bg = 'white')
genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_GV.csv', 'g20_gv', 'us_house', baf_us_house_s757) %>%
  ggsave('../charts/us_house_s757_g20_gv.png', plot = ., bg = 'white')
genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_LG.csv', 'g20_lg', 'us_house', baf_us_house_s757) %>%
  ggsave('../charts/us_house_s757_g20_lg.png', plot = ., bg = 'white')
genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_AG.csv', 'g20_ag', 'us_house', baf_us_house_s757) %>%
  ggsave('../charts/us_house_s757_g20_ag.png', plot = ., bg = 'white')

#create and save a gif of the histograms to the repo
c('../charts/us_house_s757_g20_lg.png',
  '../charts/us_house_s757_g20_uss.png',
  '../charts/us_house_s757_g20_pr.png',
  '../charts/us_house_s757_g20_ag.png',
  '../charts/us_house_s757_g20_gv.png'
) %>% 
  lapply(., image_read) %>% 
  image_join() %>% 
  image_animate(fps = 0.5) %>% 
  image_write('../charts/gifs/us_house_s757.gif')

# Creating final histogram graphics ---------------------------------------

#NC HOUSE - H898, 3RD EDITION - ENACTED
#create and save histograms to the repo
genHistogramChart('../data/ensembles/house/mcd_on/statewide_G20_PR.csv', 'g20_pr', 'nc_house', baf_nc_house_h898_ed3) %>%
  ggsave('../charts/nc_house_ed3_g20_pr.png', plot = ., bg = 'white', width = 3200, height = 1800, units = 'px')
genHistogramChart('../data/ensembles/house/mcd_on/statewide_G20_USS.csv', 'g20_uss', 'nc_house', baf_nc_house_h898_ed3) %>%
  ggsave('../charts/nc_house_ed3_g20_uss.png', plot = ., bg = 'white', width = 3200, height = 1800, units = 'px')
genHistogramChart('../data/ensembles/house/mcd_on/statewide_G20_GV.csv', 'g20_gv', 'nc_house', baf_nc_house_h898_ed3) %>%
  ggsave('../charts/nc_house_ed3_g20_gv.png', plot = ., bg = 'white', width = 3200, height = 1800, units = 'px')
genHistogramChart('../data/ensembles/house/mcd_on/statewide_G20_LG.csv', 'g20_lg', 'nc_house', baf_nc_house_h898_ed3) %>%
  ggsave('../charts/nc_house_ed3_g20_lg.png', plot = ., bg = 'white', width = 3200, height = 1800, units = 'px')
genHistogramChart('../data/ensembles/house/mcd_on/statewide_G20_AG.csv', 'g20_ag', 'nc_house', baf_nc_house_h898_ed3) %>%
  ggsave('../charts/nc_house_ed3_g20_ag.png', plot = ., bg = 'white', width = 3200, height = 1800, units = 'px')

#create and save a gif of the histograms to the repo
c('../charts/nc_house_ed3_g20_lg.png',
  '../charts/nc_house_ed3_g20_uss.png',
  '../charts/nc_house_ed3_g20_ag.png',
  '../charts/nc_house_ed3_g20_pr.png',
  '../charts/nc_house_ed3_g20_gv.png'
) %>% 
  lapply(., image_read) %>% 
  image_join() %>% 
  image_animate(fps = 0.5) %>% 
  image_write('../charts/gifs/nc_house_h898_ed3.gif')

# NC SENATE - S758, 2ND EDITION - ENACTED
#create and save histograms to the repo
genHistogramChart('../data/ensembles/senate/mcd_on/statewide_G20_PR.csv', 'g20_pr', 'nc_senate', baf_nc_senate_s758_ed2) %>%
  ggsave('../charts/nc_senate_ed2_g20_pr.png', plot = ., bg = 'white', width = 3200, height = 1800, units = 'px')
genHistogramChart('../data/ensembles/senate/mcd_on/statewide_G20_USS.csv', 'g20_uss', 'nc_senate', baf_nc_senate_s758_ed2) %>%
  ggsave('../charts/nc_senate_ed2_g20_uss.png', plot = ., bg = 'white', width = 3200, height = 1800, units = 'px')
genHistogramChart('../data/ensembles/senate/mcd_on/statewide_G20_GV.csv', 'g20_gv', 'nc_senate', baf_nc_senate_s758_ed2) %>%
  ggsave('../charts/nc_senate_ed2_g20_gv.png', plot = ., bg = 'white', width = 3200, height = 1800, units = 'px')
genHistogramChart('../data/ensembles/senate/mcd_on/statewide_G20_LG.csv', 'g20_lg', 'nc_senate', baf_nc_senate_s758_ed2) %>%
  ggsave('../charts/nc_senate_ed2_g20_lg.png', plot = ., bg = 'white', width = 3200, height = 1800, units = 'px')
genHistogramChart('../data/ensembles/senate/mcd_on/statewide_G20_AG.csv', 'g20_ag', 'nc_senate', baf_nc_senate_s758_ed2) %>%
  ggsave('../charts/nc_senate_ed2_g20_ag.png', plot = ., bg = 'white', width = 3200, height = 1800, units = 'px')

#create and save a gif of the histograms to the repo
c('../charts/nc_senate_ed2_g20_lg.png',
  '../charts/nc_senate_ed2_g20_uss.png',
  '../charts/nc_senate_ed2_g20_pr.png',
  '../charts/nc_senate_ed2_g20_ag.png',
  '../charts/nc_senate_ed2_g20_gv.png'
) %>% 
  lapply(., image_read) %>% 
  image_join() %>% 
  image_animate(fps = 0.5) %>% 
  image_write('../charts/gifs/nc_senate_s758_ed2.gif')

# US HOUSE - S757, 2ND EDITION - ENACTED
#create and save histograms to the repo
genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_PR.csv', 'g20_pr', 'us_house', baf_us_house_s757_ed2) %>%
  ggsave('../charts/us_house_s757_ed2_g20_pr.png', plot = ., bg = 'white', width = 3200, height = 1800, units = 'px')
genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_USS.csv', 'g20_uss', 'us_house', baf_us_house_s757_ed2) %>%
  ggsave('../charts/us_house_s757_ed2_g20_uss.png', plot = ., bg = 'white', width = 3200, height = 1800, units = 'px')
genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_GV.csv', 'g20_gv', 'us_house', baf_us_house_s757_ed2) %>%
  ggsave('../charts/us_house_s757_ed2_g20_gv.png', plot = ., bg = 'white', width = 3200, height = 1800, units = 'px')
genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_LG.csv', 'g20_lg', 'us_house', baf_us_house_s757_ed2) %>%
  ggsave('../charts/us_house_s757_ed2_g20_lg.png', plot = ., bg = 'white', width = 3200, height = 1800, units = 'px')
genHistogramChart('../data/ensembles/congressional/atlas_measureID12_marginals_G20_AG.csv', 'g20_ag', 'us_house', baf_us_house_s757_ed2) %>%
  ggsave('../charts/us_house_s757_ed2_g20_ag.png', plot = ., bg = 'white', width = 3200, height = 1800, units = 'px')

#create and save a gif of the histograms to the repo
c('../charts/us_house_s757_ed2_g20_lg.png',
  '../charts/us_house_s757_ed2_g20_uss.png',
  '../charts/us_house_s757_ed2_g20_pr.png',
  '../charts/us_house_s757_ed2_g20_ag.png',
  '../charts/us_house_s757_ed2_g20_gv.png'
) %>% 
  lapply(., image_read) %>% 
  image_join() %>% 
  image_animate(fps = 0.5) %>% 
  image_write('../charts/gifs/us_house_s757_ed2.gif')

# Clean and copy for GitHub -----------------------------------------------

# NC HOUSE - H898
# histogram comparison
nc_house_table %>%
  mutate(dem_pct = round(dem_pct, 1)) %>% 
  arrange(dem_pct) %>%
  select(
    'Contest & year' = race_code_parsed,
    'Statewide D vote %' = dem_pct,
    'D seats, proposed map' = dems_2023,
    'D seats, 2022 map' = dems_2022,
    'D seats, ensemble mode' = ensemble_mode,
    '# of ensemble matches' = map_count,
    'Difference, 2022' = diff_2022,
    'Difference, ensemble' = diff_ensemble
  ) %>% 
  knitr::kable('pipe') %>%
  clipr::write_clip()

#swing analysis for 2020 president
nc_house_swing_g20_pr %>%
  mutate(dem_pct = round(dem_pct, 1)) %>% 
  select(
    'Swing value' = swing_value,
    'Statewide D vote %' = dem_pct,
    'D seats, proposed map' = dems_2023,
    'D seats, 2022 map' = dems_2022,
    'D seats, ensemble mode' = hist_mode_dems,
    '% of ensemble, mode' = hist_pct
  ) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()

#swing analysis for 2020 governor
nc_house_swing_g20_gv %>%
  mutate(dem_pct = round(dem_pct, 1)) %>% 
  select(
    'Swing value' = swing_value,
    'Statewide D vote %' = dem_pct,
    'D seats, proposed map' = dems_2023,
    'D seats, 2022 map' = dems_2022,
    'D seats, ensemble mode' = hist_mode_dems,
    '% of ensemble, mode' = hist_pct
  ) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()
  
# NC SENATE - S758
# histogram comparison
nc_senate_table %>% 
  arrange(dem_pct) %>%
  select(
    'Contest & year' = race_code_parsed,
    'Statewide D vote %' = dem_pct,
    'D seats, proposed map' = dems_2023,
    'D seats, 2022 map' = dems_2022,
    'D seats, ensemble mode' = ensemble_mode,
    '# of ensemble matches' = map_count,
    'Difference, 2022' = diff_2022,
    'Difference, ensemble' = diff_ensemble
  ) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()

#swing analysis for 2020 president
nc_senate_swing_g20_pr %>%
  mutate(dem_pct = round(dem_pct, 1)) %>% 
  select(
    'Swing value' = swing_value,
    'Statewide D vote %' = dem_pct,
    'D seats, proposed map' = dems_2023,
    'D seats, 2022 map' = dems_2022,
    'D seats, ensemble mode' = hist_mode_dems,
    '% of ensemble, mode' = hist_pct
  ) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()

#swing analysis for 2020 governor
nc_senate_swing_g20_gv %>%
  mutate(dem_pct = round(dem_pct, 1)) %>% 
  select(
    'Swing value' = swing_value,
    'Statewide D vote %' = dem_pct,
    'D seats, proposed map' = dems_2023,
    'D seats, 2022 map' = dems_2022,
    'D seats, ensemble mode' = hist_mode_dems,
    '% of ensemble, mode' = hist_pct
  ) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()

# US HOUSE - S756
# histogram comparison
us_house756_table %>% 
  arrange(dem_pct) %>%
  select(
    'Contest & year' = race_code_parsed,
    'Statewide D vote %' = dem_pct,
    'D seats, proposed map' = dems_2023,
    'D seats, 2022 map' = dems_2022,
    'D seats, ensemble mode' = ensemble_mode,
    '# of ensemble matches' = map_count,
    'Difference, 2022' = diff_2022,
    'Difference, ensemble' = diff_ensemble
  ) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()

# US HOUSE - S757
# histogram comparison
us_house757_table %>% 
  arrange(dem_pct) %>%
  select(
    'Contest & year' = race_code_parsed,
    'Statewide D vote %' = dem_pct,
    'D seats, proposed map' = dems_2023,
    'D seats, 2022 map' = dems_2022,
    'D seats, ensemble mode' = ensemble_mode,
    '# of ensemble matches' = map_count,
    'Difference, 2022' = diff_2022,
    'Difference, ensemble' = diff_ensemble
  ) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()


# Clean and copy final maps for GitHub ------------------------------------

# NC HOUSE - H898
# histogram comparison
nc_house_table %>%
  mutate(dem_pct = round(dem_pct, 1)) %>% 
  arrange(dem_pct) %>%
  select(
    'Contest & year' = race_code_parsed,
    'Statewide D vote %' = dem_pct,
    'D seats, enacted map' = dems_2023_enacted,
    'D seats, proposed map' = dems_2023_filed,
    'D seats, 2022 map' = dems_2022,
    'D seats, ensemble mode' = ensemble_mode,
    '# of ensemble matches' = map_count,
    'Difference, proposed' = diff_enacted,
    'Difference, 2022' = diff_2022,
    'Difference, ensemble' = diff_ensemble
  ) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()

#swing analysis for 2020 president - ENACTED
nc_house_swing_g20_pr %>%
  mutate(dem_pct = round(dem_pct, 1)) %>% 
  select(
    'Swing value' = swing_value,
    'Statewide D vote %' = dem_pct,
    'D seats, enacted map' = dems_2023_enacted,
    'D seats, proposed map' = dems_2023_filed,
    'D seats, 2022 map' = dems_2022,
    'D seats, ensemble mode' = hist_mode_dems,
    '% of ensemble, mode' = hist_pct
  ) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()

#swing analysis for 2020 governor - ENACTED
nc_house_swing_g20_gv %>%
  mutate(dem_pct = round(dem_pct, 1)) %>% 
  select(
    'Swing value' = swing_value,
    'Statewide D vote %' = dem_pct,
    'D seats, enacted map' = dems_2023_enacted,
    'D seats, proposed map' = dems_2023_filed,
    'D seats, 2022 map' = dems_2022,
    'D seats, ensemble mode' = hist_mode_dems,
    '% of ensemble, mode' = hist_pct
  ) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()

# NC SENATE - S758
# histogram comparison
nc_senate_table %>%
  mutate(dem_pct = round(dem_pct, 1)) %>% 
  arrange(dem_pct) %>%
  select(
    'Contest & year' = race_code_parsed,
    'Statewide D vote %' = dem_pct,
    'D seats, enacted map' = dems_2023_enacted,
    'D seats, proposed map' = dems_2023_filed,
    'D seats, 2022 map' = dems_2022,
    'D seats, ensemble mode' = ensemble_mode,
    '# of ensemble matches' = map_count,
    'Difference, proposed' = diff_enacted,
    'Difference, 2022' = diff_2022,
    'Difference, ensemble' = diff_ensemble
  ) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()

#swing analysis for 2020 president - ENACTED
nc_senate_swing_g20_pr %>%
  mutate(dem_pct = round(dem_pct, 1)) %>% 
  select(
    'Swing value' = swing_value,
    'Statewide D vote %' = dem_pct,
    'D seats, enacted map' = dems_2023_enacted,
    'D seats, proposed map' = dems_2023_filed,
    'D seats, 2022 map' = dems_2022,
    'D seats, ensemble mode' = hist_mode_dems,
    '% of ensemble, mode' = hist_pct
  ) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()

#swing analysis for 2020 governor - ENACTED
nc_senate_swing_g20_gv %>%
  mutate(dem_pct = round(dem_pct, 1)) %>% 
  select(
    'Swing value' = swing_value,
    'Statewide D vote %' = dem_pct,
    'D seats, enacted map' = dems_2023_enacted,
    'D seats, proposed map' = dems_2023_filed,
    'D seats, 2022 map' = dems_2022,
    'D seats, ensemble mode' = hist_mode_dems,
    '% of ensemble, mode' = hist_pct
  ) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()

# US HOUSE - S757
# histogram comparison
us_house757_table %>%
  mutate(dem_pct = round(dem_pct, 1)) %>% 
  arrange(dem_pct) %>%
  select(
    'Contest & year' = race_code_parsed,
    'Statewide D vote %' = dem_pct,
    'D seats, enacted map' = dems_2023_enacted,
    'D seats, proposed map' = dems_2023_filed,
    'D seats, 2022 map' = dems_2022,
    'D seats, ensemble mode' = ensemble_mode,
    '# of ensemble matches' = map_count,
    'Difference, proposed' = diff_enacted,
    'Difference, 2022' = diff_2022,
    'Difference, ensemble' = diff_ensemble
  ) %>%
  knitr::kable('pipe') %>% 
  clipr::write_clip()

# Produce JSON for interactive graphics -----------------------------------

#NC House histogram graphics
genHistogramData('../data/ensembles/house/mcd_on/statewide_G20_USS.csv', 30, 80) %>% 
  select(dems_elected, map_count) %>% 
  genHistogramJSON() %>% 
  write('../data/json/histogram_g20_uss_house.json')

genHistogramData('../data/ensembles/house/mcd_on/statewide_G20_PR.csv', 30, 80) %>% 
  select(dems_elected, map_count) %>% 
  genHistogramJSON() %>% 
  write('../data/json/histogram_g20_pr_house.json')

genHistogramData('../data/ensembles/house/mcd_on/statewide_G20_GV.csv', 30, 80) %>% 
  select(dems_elected, map_count) %>% 
  genHistogramJSON() %>% 
  write('../data/json/histogram_g20_gv_house.json')

genHistogramData('../data/ensembles/house/mcd_on/statewide_G16_PR.csv', 30, 80) %>% 
  select(dems_elected, map_count) %>% 
  genHistogramJSON() %>% 
  write('../data/json/histogram_g16_pr_house.json')

#NC Senate swing analysis graphics
#single map responsiveness json
genSwingVotes(baf_nc_senate_s758, 'nc_senate', 'g20_pr', 0.005, 0.1) %>% 
  left_join(
    genEnsembleSwing('../data/ensembles/senate/mcd_on/statewide_G20_PR.csv', 'g20_pr', 0.005, 0.1),
    by = 'race_code'
  ) %>%
  mutate(dem_pct = round(total_dem_votes / total_dr_votes * 100, 1),
         republicans_single = 50 - seats,
         republicans_ensemble = 50 - hist_mode_dems) %>% 
  select(dem_pct,
         democrats_single = seats, republicans_single,
         democrats_ensemble = hist_mode_dems, republicans_ensemble) %>% 
  select(dem_pct, contains('_single')) %>% 
  rename_with(~str_remove(., '_single')) %>%
  genSwingJSON() %>% 
  write('../data/json/responsive_g20_pr_senate_proposed.json')

#ensemble map responsiveness json
genSwingVotes(baf_nc_senate_s758, 'nc_senate', 'g20_pr', 0.005, 0.1) %>% 
  left_join(
    genEnsembleSwing('../data/ensembles/senate/mcd_on/statewide_G20_PR.csv', 'g20_pr', 0.005, 0.1),
    by = 'race_code'
  ) %>%
  mutate(dem_pct = round(total_dem_votes / total_dr_votes * 100, 1),
         republicans_single = 50 - seats,
         republicans_ensemble = 50 - hist_mode_dems) %>% 
  select(dem_pct,
         democrats_single = seats, republicans_single,
         democrats_ensemble = hist_mode_dems, republicans_ensemble) %>% 
  select(dem_pct, contains('_ensemble')) %>% 
  rename_with(~str_remove(., '_ensemble')) %>%
  genSwingJSON() %>% 
  write('../data/json/responsive_g20_pr_senate_ensemble.json')